#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLIENT_INSTANCE_ID="${TIKEO_WORKER_CLIENT_INSTANCE_ID:-spring-boot3-worker-demo}"
DEMO_PORT="${TIKEO_DEMO_SERVER_PORT:-18083}"
WORKER_ENDPOINT="${TIKEO_WORKER_ENDPOINT:-http://127.0.0.1:9998}"
WORKER_NAMESPACE="${TIKEO_WORKER_NAMESPACE:-dev-alpha}"
WORKER_APP="${TIKEO_WORKER_APP:-orders}"
WORKER_POOL="${TIKEO_WORKER_POOL:-boot3-blue}"
WORKER_CLUSTER="${TIKEO_WORKER_CLUSTER:-local}"
WORKER_REGION="${TIKEO_WORKER_REGION:-local}"
STATE_DIR="${TIKEO_WORKER_STATE_DIR:-$ROOT_DIR/.dev/$CLIENT_INSTANCE_ID-state}"
ELECTION_DOMAIN="${TIKEO_WORKER_ELECTION_DOMAIN:-$WORKER_NAMESPACE/$WORKER_APP/$WORKER_POOL/$WORKER_CLUSTER}"
ELECTION_PRIORITY="${TIKEO_WORKER_ELECTION_PRIORITY:-100}"
SCRIPT_RUNTIME_CHECK="${TIKEO_WORKER_SCRIPT_RUNTIME_CHECK:-true}"
SCRIPT_AUTO_INSTALL_TOOLS="${TIKEO_WORKER_SCRIPT_AUTO_INSTALL_TOOLS:-true}"
WASM_AUTO_INSTALL="${TIKEO_WORKER_WASM_AUTO_INSTALL:-true}"
MANAGEMENT_NAMESPACE="${TIKEO_MANAGEMENT_NAMESPACE:-$WORKER_NAMESPACE}"
MANAGEMENT_APP="${TIKEO_MANAGEMENT_APP:-$WORKER_APP}"

mkdir -p "$STATE_DIR"
cd "$ROOT_DIR"
TIKEO_WORKER_DRY_RUN="${TIKEO_WORKER_DRY_RUN:-false}" \
TIKEO_WORKER_ENDPOINT="$WORKER_ENDPOINT" \
TIKEO_WORKER_NAMESPACE="$WORKER_NAMESPACE" \
TIKEO_WORKER_APP="$WORKER_APP" \
TIKEO_WORKER_POOL="$WORKER_POOL" \
TIKEO_WORKER_CLUSTER="$WORKER_CLUSTER" \
TIKEO_WORKER_REGION="$WORKER_REGION" \
TIKEO_DEMO_SERVER_PORT="$DEMO_PORT" \
TIKEO_WORKER_CLIENT_INSTANCE_ID="$CLIENT_INSTANCE_ID" \
TIKEO_WORKER_STATE_DIR="$STATE_DIR" \
TIKEO_WORKER_ELECTION_DOMAIN="$ELECTION_DOMAIN" \
TIKEO_WORKER_ELECTION_PRIORITY="$ELECTION_PRIORITY" \
TIKEO_WORKER_SCRIPT_RUNTIME_CHECK="$SCRIPT_RUNTIME_CHECK" \
TIKEO_WORKER_SCRIPT_AUTO_INSTALL_TOOLS="$SCRIPT_AUTO_INSTALL_TOOLS" \
TIKEO_WORKER_WASM_AUTO_INSTALL="$WASM_AUTO_INSTALL" \
TIKEO_MANAGEMENT_NAMESPACE="$MANAGEMENT_NAMESPACE" \
TIKEO_MANAGEMENT_APP="$MANAGEMENT_APP" \
exec ./gradlew bootRun --no-daemon
