#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLIENT_INSTANCE_ID="${TIKEE_WORKER_CLIENT_INSTANCE_ID:-spring-boot3-worker-demo}"
DEMO_PORT="${TIKEE_DEMO_SERVER_PORT:-18083}"
WORKER_ENDPOINT="${TIKEE_WORKER_ENDPOINT:-http://127.0.0.1:9998}"
WORKER_NAMESPACE="${TIKEE_WORKER_NAMESPACE:-default}"
WORKER_APP="${TIKEE_WORKER_APP:-default}"
WORKER_POOL="${TIKEE_WORKER_POOL:-default}"
WORKER_CLUSTER="${TIKEE_WORKER_CLUSTER:-local}"
WORKER_REGION="${TIKEE_WORKER_REGION:-local}"
STATE_DIR="${TIKEE_WORKER_STATE_DIR:-$ROOT_DIR/.dev/$CLIENT_INSTANCE_ID-state}"
ELECTION_DOMAIN="${TIKEE_WORKER_ELECTION_DOMAIN:-$WORKER_NAMESPACE/$WORKER_APP/$WORKER_POOL/$WORKER_CLUSTER}"
ELECTION_PRIORITY="${TIKEE_WORKER_ELECTION_PRIORITY:-100}"

mkdir -p "$STATE_DIR"
cd "$ROOT_DIR"
TIKEE_WORKER_DRY_RUN="${TIKEE_WORKER_DRY_RUN:-false}" \
TIKEE_WORKER_ENDPOINT="$WORKER_ENDPOINT" \
TIKEE_WORKER_NAMESPACE="$WORKER_NAMESPACE" \
TIKEE_WORKER_APP="$WORKER_APP" \
TIKEE_WORKER_POOL="$WORKER_POOL" \
TIKEE_WORKER_CLUSTER="$WORKER_CLUSTER" \
TIKEE_WORKER_REGION="$WORKER_REGION" \
TIKEE_DEMO_SERVER_PORT="$DEMO_PORT" \
TIKEE_WORKER_CLIENT_INSTANCE_ID="$CLIENT_INSTANCE_ID" \
TIKEE_WORKER_STATE_DIR="$STATE_DIR" \
TIKEE_WORKER_ELECTION_DOMAIN="$ELECTION_DOMAIN" \
TIKEE_WORKER_ELECTION_PRIORITY="$ELECTION_PRIORITY" \
exec ./gradlew bootRun --no-daemon
