// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*WorkerMessage_Register
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_TaskResult
	//	*WorkerMessage_TaskLog
	//	*WorkerMessage_Unregister
	//	*WorkerMessage_TaskCheckpoint
	Kind          isWorkerMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetKind() isWorkerMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *WorkerMessage) GetRegister() *RegisterWorker {
	if x != nil {
		if x, ok := x.Kind.(*WorkerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Kind.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Kind.(*WorkerMessage_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskLog() *TaskLog {
	if x != nil {
		if x, ok := x.Kind.(*WorkerMessage_TaskLog); ok {
			return x.TaskLog
		}
	}
	return nil
}

func (x *WorkerMessage) GetUnregister() *UnregisterWorker {
	if x != nil {
		if x, ok := x.Kind.(*WorkerMessage_Unregister); ok {
			return x.Unregister
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskCheckpoint() *TaskCheckpoint {
	if x != nil {
		if x, ok := x.Kind.(*WorkerMessage_TaskCheckpoint); ok {
			return x.TaskCheckpoint
		}
	}
	return nil
}

type isWorkerMessage_Kind interface {
	isWorkerMessage_Kind()
}

type WorkerMessage_Register struct {
	Register *RegisterWorker `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,3,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type WorkerMessage_TaskLog struct {
	TaskLog *TaskLog `protobuf:"bytes,4,opt,name=task_log,json=taskLog,proto3,oneof"`
}

type WorkerMessage_Unregister struct {
	Unregister *UnregisterWorker `protobuf:"bytes,5,opt,name=unregister,proto3,oneof"`
}

type WorkerMessage_TaskCheckpoint struct {
	TaskCheckpoint *TaskCheckpoint `protobuf:"bytes,6,opt,name=task_checkpoint,json=taskCheckpoint,proto3,oneof"`
}

func (*WorkerMessage_Register) isWorkerMessage_Kind() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Kind() {}

func (*WorkerMessage_TaskResult) isWorkerMessage_Kind() {}

func (*WorkerMessage_TaskLog) isWorkerMessage_Kind() {}

func (*WorkerMessage_Unregister) isWorkerMessage_Kind() {}

func (*WorkerMessage_TaskCheckpoint) isWorkerMessage_Kind() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ServerMessage_Registered
	//	*ServerMessage_Ping
	//	*ServerMessage_DispatchTask
	Kind          isServerMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetKind() isServerMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ServerMessage) GetRegistered() *WorkerRegistered {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *ServerMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ServerMessage) GetDispatchTask() *DispatchTask {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_DispatchTask); ok {
			return x.DispatchTask
		}
	}
	return nil
}

type isServerMessage_Kind interface {
	isServerMessage_Kind()
}

type ServerMessage_Registered struct {
	Registered *WorkerRegistered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type ServerMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type ServerMessage_DispatchTask struct {
	DispatchTask *DispatchTask `protobuf:"bytes,3,opt,name=dispatch_task,json=dispatchTask,proto3,oneof"`
}

func (*ServerMessage_Registered) isServerMessage_Kind() {}

func (*ServerMessage_Ping) isServerMessage_Kind() {}

func (*ServerMessage_DispatchTask) isServerMessage_Kind() {}

type RegisterWorker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional client-side stable instance hint. The tikeo still assigns the authoritative worker_id.
	ClientInstanceId string `protobuf:"bytes,1,opt,name=client_instance_id,json=clientInstanceId,proto3" json:"client_instance_id,omitempty"`
	App              string `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Namespace        string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Cluster          string `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Region           string `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	// Legacy free-form labels/capabilities. New routing must use structured_capabilities.
	Capabilities           []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Labels                 map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StructuredCapabilities *WorkerCapabilities    `protobuf:"bytes,8,opt,name=structured_capabilities,json=structuredCapabilities,proto3" json:"structured_capabilities,omitempty"`
	Election               *WorkerClusterElection `protobuf:"bytes,9,opt,name=election,proto3" json:"election,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterWorker) Reset() {
	*x = RegisterWorker{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorker) ProtoMessage() {}

func (x *RegisterWorker) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorker.ProtoReflect.Descriptor instead.
func (*RegisterWorker) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterWorker) GetClientInstanceId() string {
	if x != nil {
		return x.ClientInstanceId
	}
	return ""
}

func (x *RegisterWorker) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *RegisterWorker) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RegisterWorker) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *RegisterWorker) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterWorker) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterWorker) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterWorker) GetStructuredCapabilities() *WorkerCapabilities {
	if x != nil {
		return x.StructuredCapabilities
	}
	return nil
}

func (x *RegisterWorker) GetElection() *WorkerClusterElection {
	if x != nil {
		return x.Election
	}
	return nil
}

type WorkerCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human/operator tags such as java or spring-boot. Not used for dispatch routing.
	Tags             []string                     `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	NormalProcessors []*ProcessorCapability       `protobuf:"bytes,2,rep,name=normal_processors,json=normalProcessors,proto3" json:"normal_processors,omitempty"`
	ScriptRunners    []*ScriptRunnerCapability    `protobuf:"bytes,3,rep,name=script_runners,json=scriptRunners,proto3" json:"script_runners,omitempty"`
	PluginProcessors []*PluginProcessorCapability `protobuf:"bytes,4,rep,name=plugin_processors,json=pluginProcessors,proto3" json:"plugin_processors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkerCapabilities) Reset() {
	*x = WorkerCapabilities{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerCapabilities) ProtoMessage() {}

func (x *WorkerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerCapabilities.ProtoReflect.Descriptor instead.
func (*WorkerCapabilities) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerCapabilities) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *WorkerCapabilities) GetNormalProcessors() []*ProcessorCapability {
	if x != nil {
		return x.NormalProcessors
	}
	return nil
}

func (x *WorkerCapabilities) GetScriptRunners() []*ScriptRunnerCapability {
	if x != nil {
		return x.ScriptRunners
	}
	return nil
}

func (x *WorkerCapabilities) GetPluginProcessors() []*PluginProcessorCapability {
	if x != nil {
		return x.PluginProcessors
	}
	return nil
}

type ProcessorCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessorCapability) Reset() {
	*x = ProcessorCapability{}
	mi := &file_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessorCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessorCapability) ProtoMessage() {}

func (x *ProcessorCapability) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessorCapability.ProtoReflect.Descriptor instead.
func (*ProcessorCapability) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessorCapability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessorCapability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ScriptRunnerCapability struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Language       string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	SandboxBackend string                 `protobuf:"bytes,2,opt,name=sandbox_backend,json=sandboxBackend,proto3" json:"sandbox_backend,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScriptRunnerCapability) Reset() {
	*x = ScriptRunnerCapability{}
	mi := &file_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptRunnerCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptRunnerCapability) ProtoMessage() {}

func (x *ScriptRunnerCapability) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptRunnerCapability.ProtoReflect.Descriptor instead.
func (*ScriptRunnerCapability) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ScriptRunnerCapability) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ScriptRunnerCapability) GetSandboxBackend() string {
	if x != nil {
		return x.SandboxBackend
	}
	return ""
}

type PluginProcessorCapability struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ProcessorNames []string               `protobuf:"bytes,2,rep,name=processor_names,json=processorNames,proto3" json:"processor_names,omitempty"`
	// Rich processor list carrying display metadata for operator UI.
	Processors    []*ProcessorCapability `protobuf:"bytes,3,rep,name=processors,proto3" json:"processors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginProcessorCapability) Reset() {
	*x = PluginProcessorCapability{}
	mi := &file_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginProcessorCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginProcessorCapability) ProtoMessage() {}

func (x *PluginProcessorCapability) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginProcessorCapability.ProtoReflect.Descriptor instead.
func (*PluginProcessorCapability) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{6}
}

func (x *PluginProcessorCapability) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PluginProcessorCapability) GetProcessorNames() []string {
	if x != nil {
		return x.ProcessorNames
	}
	return nil
}

func (x *PluginProcessorCapability) GetProcessors() []*ProcessorCapability {
	if x != nil {
		return x.Processors
	}
	return nil
}

type WorkerClusterElection struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enabled bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Stable election domain. Empty means namespace/app/cluster/region.
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// Optional deterministic priority. Lower values win ties after health checks.
	Priority      uint32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerClusterElection) Reset() {
	*x = WorkerClusterElection{}
	mi := &file_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerClusterElection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerClusterElection) ProtoMessage() {}

func (x *WorkerClusterElection) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerClusterElection.ProtoReflect.Descriptor instead.
func (*WorkerClusterElection) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerClusterElection) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WorkerClusterElection) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *WorkerClusterElection) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Generation    uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	FencingToken  string                 `protobuf:"bytes,4,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Heartbeat) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Heartbeat) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Heartbeat) GetFencingToken() string {
	if x != nil {
		return x.FencingToken
	}
	return ""
}

type WorkerRegistered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LeaseSeconds  uint64                 `protobuf:"varint,2,opt,name=lease_seconds,json=leaseSeconds,proto3" json:"lease_seconds,omitempty"`
	Generation    uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	FencingToken  string                 `protobuf:"bytes,4,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRegistered) Reset() {
	*x = WorkerRegistered{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegistered) ProtoMessage() {}

func (x *WorkerRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegistered.ProtoReflect.Descriptor instead.
func (*WorkerRegistered) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *WorkerRegistered) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerRegistered) GetLeaseSeconds() uint64 {
	if x != nil {
		return x.LeaseSeconds
	}
	return 0
}

func (x *WorkerRegistered) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *WorkerRegistered) GetFencingToken() string {
	if x != nil {
		return x.FencingToken
	}
	return ""
}

type UnregisterWorker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	FencingToken  string                 `protobuf:"bytes,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterWorker) Reset() {
	*x = UnregisterWorker{}
	mi := &file_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterWorker) ProtoMessage() {}

func (x *UnregisterWorker) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterWorker.ProtoReflect.Descriptor instead.
func (*UnregisterWorker) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{10}
}

func (x *UnregisterWorker) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *UnregisterWorker) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *UnregisterWorker) GetFencingToken() string {
	if x != nil {
		return x.FencingToken
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{11}
}

func (x *Ping) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type DispatchTask struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	JobId      string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Payload    []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Explicit processor key used by SDK adapters. Defaults to job_id for backwards compatibility.
	ProcessorName string `protobuf:"bytes,4,opt,name=processor_name,json=processorName,proto3" json:"processor_name,omitempty"`
	// Optional dynamic processor metadata. Empty for normal processors.
	ProcessorBinding *TaskProcessorBinding `protobuf:"bytes,5,opt,name=processor_binding,json=processorBinding,proto3" json:"processor_binding,omitempty"`
	// Server-issued opaque assignment authority bound to worker session generation/fencing.
	AssignmentToken string `protobuf:"bytes,6,opt,name=assignment_token,json=assignmentToken,proto3" json:"assignment_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DispatchTask) Reset() {
	*x = DispatchTask{}
	mi := &file_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTask) ProtoMessage() {}

func (x *DispatchTask) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTask.ProtoReflect.Descriptor instead.
func (*DispatchTask) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{12}
}

func (x *DispatchTask) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DispatchTask) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DispatchTask) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DispatchTask) GetProcessorName() string {
	if x != nil {
		return x.ProcessorName
	}
	return ""
}

func (x *DispatchTask) GetProcessorBinding() *TaskProcessorBinding {
	if x != nil {
		return x.ProcessorBinding
	}
	return nil
}

func (x *DispatchTask) GetAssignmentToken() string {
	if x != nil {
		return x.AssignmentToken
	}
	return ""
}

type TaskProcessorBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*TaskProcessorBinding_Wasm
	//	*TaskProcessorBinding_Script
	Kind          isTaskProcessorBinding_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProcessorBinding) Reset() {
	*x = TaskProcessorBinding{}
	mi := &file_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProcessorBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProcessorBinding) ProtoMessage() {}

func (x *TaskProcessorBinding) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProcessorBinding.ProtoReflect.Descriptor instead.
func (*TaskProcessorBinding) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{13}
}

func (x *TaskProcessorBinding) GetKind() isTaskProcessorBinding_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *TaskProcessorBinding) GetWasm() *WasmProcessorBinding {
	if x != nil {
		if x, ok := x.Kind.(*TaskProcessorBinding_Wasm); ok {
			return x.Wasm
		}
	}
	return nil
}

func (x *TaskProcessorBinding) GetScript() *ScriptProcessorBinding {
	if x != nil {
		if x, ok := x.Kind.(*TaskProcessorBinding_Script); ok {
			return x.Script
		}
	}
	return nil
}

type isTaskProcessorBinding_Kind interface {
	isTaskProcessorBinding_Kind()
}

type TaskProcessorBinding_Wasm struct {
	Wasm *WasmProcessorBinding `protobuf:"bytes,1,opt,name=wasm,proto3,oneof"`
}

type TaskProcessorBinding_Script struct {
	Script *ScriptProcessorBinding `protobuf:"bytes,2,opt,name=script,proto3,oneof"`
}

func (*TaskProcessorBinding_Wasm) isTaskProcessorBinding_Kind() {}

func (*TaskProcessorBinding_Script) isTaskProcessorBinding_Kind() {}
