use sea_orm::{
    ActiveModelTrait, ColumnTrait, DatabaseConnection, EntityTrait, QueryFilter, QueryOrder,
    QuerySelect, Set,
};
use serde::{Deserialize, Serialize};

use crate::entities::{
    raft_applied_command, raft_log_entry, raft_member, raft_membership_proposal, raft_metadata,
    raft_snapshot,
};

use super::util::{new_id, now_rfc3339};

/// Raft metadata upsert input.
#[derive(Debug, Clone)]
pub struct UpsertRaftMetadata {
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable local node id.
    pub node_id: String,
    /// Last known Raft term.
    pub current_term: i64,
    /// Vote target in the current term.
    pub voted_for: Option<String>,
    /// Last committed index.
    pub commit_index: i64,
    /// Last applied index.
    pub applied_index: i64,
    /// Leader fencing token generated by a real consensus runtime, when any.
    pub leader_fencing_token: Option<String>,
    /// Base64-encoded raft-rs `ConfState`, when dynamic membership has been applied.
    pub conf_state: Option<String>,
}

/// Raft member upsert input.
#[derive(Debug, Clone)]
pub struct UpsertRaftMember {
    /// Stable member node id.
    pub node_id: String,
    /// Peer endpoint reachable through container/K8s networking.
    pub endpoint: String,
    /// Member lifecycle status.
    pub status: String,
}

/// Raft log entry upsert input. Payloads are encoded by the caller.
#[derive(Debug, Clone)]
pub struct UpsertRaftLogEntry {
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable tikeo node id owning this local log.
    pub node_id: String,
    /// Raft log index.
    pub log_index: i64,
    /// Raft term.
    pub term: i64,
    /// raft-rs entry type name.
    pub entry_type: String,
    /// Base64-encoded entry payload bytes.
    pub data: String,
    /// Base64-encoded entry context bytes.
    pub context: Option<String>,
    /// Persistence status used by the future Ready pipeline.
    pub sync_status: String,
}

/// Raft snapshot upsert input. Payloads are encoded by the caller.
#[derive(Debug, Clone)]
pub struct UpsertRaftSnapshot {
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable tikeo node id owning this local snapshot.
    pub node_id: String,
    /// Snapshot index.
    pub snapshot_index: i64,
    /// Snapshot term.
    pub term: i64,
    /// Base64-encoded `ConfState` bytes or JSON marker.
    pub conf_state: Option<String>,
    /// Base64-encoded snapshot data or object-store pointer.
    pub data: Option<String>,
}

/// Applied Raft command insert input.
#[derive(Debug, Clone)]
pub struct RecordRaftAppliedCommand {
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable local node id.
    pub node_id: String,
    /// Raft log index.
    pub log_index: i64,
    /// Raft term.
    pub term: i64,
    /// Idempotency key from the command envelope.
    pub command_id: String,
    /// Command type.
    pub command_type: String,
    /// Captured payload.
    pub payload: Option<String>,
    /// Apply status.
    pub status: String,
    /// Human-readable result.
    pub message: String,
}

/// Membership proposal insert input.
#[derive(Debug, Clone)]
pub struct RecordRaftMembershipProposal {
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Proposal idempotency key.
    pub proposal_id: String,
    /// Membership action.
    pub action: String,
    /// Target node id.
    pub node_id: String,
    /// Target endpoint for add/update actions.
    pub endpoint: Option<String>,
    /// Proposal status.
    pub status: String,
    /// Human-readable result.
    pub message: String,
    /// Authenticated actor.
    pub created_by: String,
}

/// Stored Raft metadata summary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RaftMetadataSummary {
    /// Metadata row identifier.
    pub id: String,
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable local node id.
    pub node_id: String,
    /// Last known Raft term.
    pub current_term: i64,
    /// Vote target in the current term.
    pub voted_for: Option<String>,
    /// Last committed index.
    pub commit_index: i64,
    /// Last applied index.
    pub applied_index: i64,
    /// Leader fencing token generated by a real consensus runtime, when any.
    pub leader_fencing_token: Option<String>,
    /// Base64-encoded raft-rs `ConfState`, when dynamic membership has been applied.
    pub conf_state: Option<String>,
    /// Last update timestamp.
    pub updated_at: String,
}

/// Stored Raft member summary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RaftMemberSummary {
    /// Member row identifier.
    pub id: String,
    /// Stable member node id.
    pub node_id: String,
    /// Peer endpoint reachable through container/K8s networking.
    pub endpoint: String,
    /// Member lifecycle status.
    pub status: String,
    /// Creation timestamp.
    pub created_at: String,
    /// Last update timestamp.
    pub updated_at: String,
}

/// Stored Raft log entry summary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RaftLogEntrySummary {
    /// Log row identifier.
    pub id: String,
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable tikeo node id owning this local log.
    pub node_id: String,
    /// Raft log index.
    pub log_index: i64,
    /// Raft term.
    pub term: i64,
    /// raft-rs entry type name.
    pub entry_type: String,
    /// Base64-encoded entry payload bytes.
    pub data: String,
    /// Base64-encoded entry context bytes.
    pub context: Option<String>,
    /// Persistence status used by the future Ready pipeline.
    pub sync_status: String,
    /// Creation timestamp.
    pub created_at: String,
    /// Last update timestamp.
    pub updated_at: String,
}

/// Stored Raft snapshot summary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RaftSnapshotSummary {
    /// Snapshot row identifier.
    pub id: String,
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable tikeo node id owning this local snapshot.
    pub node_id: String,
    /// Snapshot index.
    pub snapshot_index: i64,
    /// Snapshot term.
    pub term: i64,
    /// Base64-encoded `ConfState` bytes or JSON marker.
    pub conf_state: Option<String>,
    /// Base64-encoded snapshot data or object-store pointer.
    pub data: Option<String>,
    /// Creation timestamp.
    pub created_at: String,
    /// Last update timestamp.
    pub updated_at: String,
}

/// Stored applied Raft command summary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RaftAppliedCommandSummary {
    /// Row identifier.
    pub id: String,
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable local node id.
    pub node_id: String,
    /// Raft log index.
    pub log_index: i64,
    /// Raft term.
    pub term: i64,
    /// Command idempotency key.
    pub command_id: String,
    /// Command type.
    pub command_type: String,
    /// Captured payload.
    pub payload: Option<String>,
    /// Apply status.
    pub status: String,
    /// Human-readable result.
    pub message: String,
    /// Creation timestamp.
    pub created_at: String,
    /// Last update timestamp.
    pub updated_at: String,
}

/// Stored Raft membership proposal summary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
pub struct RaftMembershipProposalSummary {
    /// Row identifier.
    pub id: String,
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Proposal idempotency key.
    pub proposal_id: String,
    /// Membership action.
    pub action: String,
    /// Target node id.
    pub node_id: String,
    /// Target endpoint.
    pub endpoint: Option<String>,
    /// Proposal status.
    pub status: String,
    /// Human-readable result.
    pub message: String,
    /// Authenticated actor.
    pub created_by: String,
    /// Creation timestamp.
    pub created_at: String,
    /// Last update timestamp.
    pub updated_at: String,
}

/// Repository for Raft metadata, membership, and future raft-rs durable records.
#[derive(Debug, Clone)]
pub struct RaftRepository {
    db: DatabaseConnection,
}

impl RaftRepository {
    /// Create a repository using the provided database connection.
    #[must_use]
    /// New.
    pub const fn new(db: DatabaseConnection) -> Self {
        Self { db }
    }

    /// Clone the underlying database handle for repositories that need the same transaction scope.
    #[must_use]
    /// Db.
    pub fn db(&self) -> DatabaseConnection {
        self.db.clone()
    }

    /// Upsert local Raft metadata by `node_id`.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn upsert_metadata(
        &self,
        input: UpsertRaftMetadata,
    ) -> Result<RaftMetadataSummary, sea_orm::DbErr> {
        let now = now_rfc3339();
        if let Some(existing) = raft_metadata::Entity::find()
            .filter(raft_metadata::Column::NodeId.eq(input.node_id.clone()))
            .one(&self.db)
            .await?
        {
            let mut active: raft_metadata::ActiveModel = existing.into();
            active.cluster_id = Set(input.cluster_id);
            active.current_term = Set(input.current_term);
            active.voted_for = Set(input.voted_for);
            active.commit_index = Set(input.commit_index);
            active.applied_index = Set(input.applied_index);
            active.leader_fencing_token = Set(input.leader_fencing_token);
            active.conf_state = Set(input.conf_state);
            active.updated_at = Set(now);
            return active.update(&self.db).await.map(RaftMetadataSummary::from);
        }

        raft_metadata::ActiveModel {
            id: Set(new_id("raft_meta")),
            cluster_id: Set(input.cluster_id),
            node_id: Set(input.node_id),
            current_term: Set(input.current_term),
            voted_for: Set(input.voted_for),
            commit_index: Set(input.commit_index),
            applied_index: Set(input.applied_index),
            leader_fencing_token: Set(input.leader_fencing_token),
            conf_state: Set(input.conf_state),
            updated_at: Set(now),
        }
        .insert(&self.db)
        .await
        .map(RaftMetadataSummary::from)
    }

    /// Return local Raft metadata by `node_id`.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn get_metadata(
        &self,
        node_id: &str,
    ) -> Result<Option<RaftMetadataSummary>, sea_orm::DbErr> {
        raft_metadata::Entity::find()
            .filter(raft_metadata::Column::NodeId.eq(node_id.to_owned()))
            .one(&self.db)
            .await
            .map(|row| row.map(RaftMetadataSummary::from))
    }

    /// Monotonically update the local applied index for a Raft node.
    ///
    /// Returns the current row when it exists. If the requested index is older than the
    /// stored value, the stored value is preserved.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn update_applied_index(
        &self,
        node_id: &str,
        applied_index: i64,
    ) -> Result<Option<RaftMetadataSummary>, sea_orm::DbErr> {
        let Some(existing) = raft_metadata::Entity::find()
            .filter(raft_metadata::Column::NodeId.eq(node_id.to_owned()))
            .one(&self.db)
            .await?
        else {
            return Ok(None);
        };
        if applied_index <= existing.applied_index {
            return Ok(Some(existing.into()));
        }

        let now = now_rfc3339();
        let mut active: raft_metadata::ActiveModel = existing.into();
        active.applied_index = Set(applied_index);
        active.updated_at = Set(now);
        active
            .update(&self.db)
            .await
            .map(RaftMetadataSummary::from)
            .map(Some)
    }

    /// Update only the local leader fencing token for a Raft node.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn update_leader_fencing_token(
        &self,
        node_id: &str,
        leader_fencing_token: Option<String>,
    ) -> Result<Option<RaftMetadataSummary>, sea_orm::DbErr> {
        let Some(existing) = raft_metadata::Entity::find()
            .filter(raft_metadata::Column::NodeId.eq(node_id.to_owned()))
            .one(&self.db)
            .await?
        else {
            return Ok(None);
        };
        if existing.leader_fencing_token == leader_fencing_token {
            return Ok(Some(existing.into()));
        }

        let now = now_rfc3339();
        let mut active: raft_metadata::ActiveModel = existing.into();
        active.leader_fencing_token = Set(leader_fencing_token);
        active.updated_at = Set(now);
        active
            .update(&self.db)
            .await
            .map(RaftMetadataSummary::from)
            .map(Some)
    }

    /// Update only the local persisted raft-rs `ConfState` for a Raft node.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn update_conf_state(
        &self,
        node_id: &str,
        conf_state: String,
    ) -> Result<Option<RaftMetadataSummary>, sea_orm::DbErr> {
        let Some(existing) = raft_metadata::Entity::find()
            .filter(raft_metadata::Column::NodeId.eq(node_id.to_owned()))
            .one(&self.db)
            .await?
        else {
            return Ok(None);
        };
        if existing.conf_state.as_deref() == Some(conf_state.as_str()) {
            return Ok(Some(existing.into()));
        }

        let now = now_rfc3339();
        let mut active: raft_metadata::ActiveModel = existing.into();
        active.conf_state = Set(Some(conf_state));
        active.updated_at = Set(now);
        active
            .update(&self.db)
            .await
            .map(RaftMetadataSummary::from)
            .map(Some)
    }

    /// Upsert a configured Raft member by `node_id`.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn upsert_member(
        &self,
        input: UpsertRaftMember,
    ) -> Result<RaftMemberSummary, sea_orm::DbErr> {
        let now = now_rfc3339();
        if let Some(existing) = raft_member::Entity::find()
            .filter(raft_member::Column::NodeId.eq(input.node_id.clone()))
            .one(&self.db)
            .await?
        {
            let mut active: raft_member::ActiveModel = existing.into();
            active.endpoint = Set(input.endpoint);
            active.status = Set(input.status);
            active.updated_at = Set(now);
            return active.update(&self.db).await.map(RaftMemberSummary::from);
        }

        raft_member::ActiveModel {
            id: Set(new_id("raft_member")),
            node_id: Set(input.node_id),
            endpoint: Set(input.endpoint),
            status: Set(input.status),
            created_at: Set(now.clone()),
            updated_at: Set(now),
        }
        .insert(&self.db)
        .await
        .map(RaftMemberSummary::from)
    }

    /// List all configured Raft members.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn list_members(&self) -> Result<Vec<RaftMemberSummary>, sea_orm::DbErr> {
        raft_member::Entity::find()
            .all(&self.db)
            .await
            .map(|rows| rows.into_iter().map(RaftMemberSummary::from).collect())
    }

    /// Return a configured Raft member by `node_id`.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn get_member(
        &self,
        node_id: &str,
    ) -> Result<Option<RaftMemberSummary>, sea_orm::DbErr> {
        raft_member::Entity::find()
            .filter(raft_member::Column::NodeId.eq(node_id.to_owned()))
            .one(&self.db)
            .await
            .map(|row| row.map(RaftMemberSummary::from))
    }

    /// Upsert a local raft-rs log entry by `(node_id, log_index)`.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn upsert_log_entry(
        &self,
        input: UpsertRaftLogEntry,
    ) -> Result<RaftLogEntrySummary, sea_orm::DbErr> {
        let now = now_rfc3339();
        if let Some(existing) = raft_log_entry::Entity::find()
            .filter(raft_log_entry::Column::NodeId.eq(input.node_id.clone()))
            .filter(raft_log_entry::Column::LogIndex.eq(input.log_index))
            .one(&self.db)
            .await?
        {
            let mut active: raft_log_entry::ActiveModel = existing.into();
            active.cluster_id = Set(input.cluster_id);
            active.term = Set(input.term);
            active.entry_type = Set(input.entry_type);
            active.data = Set(input.data);
            active.context = Set(input.context);
            active.sync_status = Set(input.sync_status);
            active.updated_at = Set(now);
            return active.update(&self.db).await.map(RaftLogEntrySummary::from);
        }

        raft_log_entry::ActiveModel {
            id: Set(new_id("raft_log")),
            cluster_id: Set(input.cluster_id),
            node_id: Set(input.node_id),
            log_index: Set(input.log_index),
            term: Set(input.term),
            entry_type: Set(input.entry_type),
            data: Set(input.data),
            context: Set(input.context),
            sync_status: Set(input.sync_status),
            created_at: Set(now.clone()),
            updated_at: Set(now),
        }
        .insert(&self.db)
        .await
        .map(RaftLogEntrySummary::from)
    }

    /// List local raft-rs log entries from `from_index` inclusive.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn list_log_entries(
        &self,
        node_id: &str,
        from_index: i64,
        limit: u64,
    ) -> Result<Vec<RaftLogEntrySummary>, sea_orm::DbErr> {
        raft_log_entry::Entity::find()
            .filter(raft_log_entry::Column::NodeId.eq(node_id.to_owned()))
            .filter(raft_log_entry::Column::LogIndex.gte(from_index))
            .order_by_asc(raft_log_entry::Column::LogIndex)
            .limit(limit)
            .all(&self.db)
            .await
            .map(|rows| rows.into_iter().map(RaftLogEntrySummary::from).collect())
    }

    /// Upsert a local raft-rs snapshot by `(node_id, snapshot_index)`.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn upsert_snapshot(
        &self,
        input: UpsertRaftSnapshot,
    ) -> Result<RaftSnapshotSummary, sea_orm::DbErr> {
        let now = now_rfc3339();
        if let Some(existing) = raft_snapshot::Entity::find()
            .filter(raft_snapshot::Column::NodeId.eq(input.node_id.clone()))
            .filter(raft_snapshot::Column::SnapshotIndex.eq(input.snapshot_index))
            .one(&self.db)
            .await?
        {
            let mut active: raft_snapshot::ActiveModel = existing.into();
            active.cluster_id = Set(input.cluster_id);
            active.term = Set(input.term);
            active.conf_state = Set(input.conf_state);
            active.data = Set(input.data);
            active.updated_at = Set(now);
            return active.update(&self.db).await.map(RaftSnapshotSummary::from);
        }

        raft_snapshot::ActiveModel {
            id: Set(new_id("raft_snapshot")),
            cluster_id: Set(input.cluster_id),
            node_id: Set(input.node_id),
            snapshot_index: Set(input.snapshot_index),
            term: Set(input.term),
            conf_state: Set(input.conf_state),
            data: Set(input.data),
            created_at: Set(now.clone()),
            updated_at: Set(now),
        }
        .insert(&self.db)
        .await
        .map(RaftSnapshotSummary::from)
    }

    /// Record an applied Raft command idempotently by `(node_id, log_index)`.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn record_applied_command(
        &self,
        input: RecordRaftAppliedCommand,
    ) -> Result<RaftAppliedCommandSummary, sea_orm::DbErr> {
        if let Some(existing) = raft_applied_command::Entity::find()
            .filter(raft_applied_command::Column::NodeId.eq(input.node_id.clone()))
            .filter(raft_applied_command::Column::LogIndex.eq(input.log_index))
            .one(&self.db)
            .await?
        {
            return Ok(existing.into());
        }
        if let Some(existing) = raft_applied_command::Entity::find()
            .filter(raft_applied_command::Column::ClusterId.eq(input.cluster_id.clone()))
            .filter(raft_applied_command::Column::CommandId.eq(input.command_id.clone()))
            .one(&self.db)
            .await?
        {
            return Ok(existing.into());
        }

        let now = now_rfc3339();
        raft_applied_command::ActiveModel {
            id: Set(new_id("raft_cmd")),
            cluster_id: Set(input.cluster_id),
            node_id: Set(input.node_id),
            log_index: Set(input.log_index),
            term: Set(input.term),
            command_id: Set(input.command_id),
            command_type: Set(input.command_type),
            payload: Set(input.payload),
            status: Set(input.status),
            message: Set(input.message),
            created_at: Set(now.clone()),
            updated_at: Set(now),
        }
        .insert(&self.db)
        .await
        .map(RaftAppliedCommandSummary::from)
    }

    /// Return an applied Raft command by its cluster-wide idempotency key.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn get_applied_command_by_command_id(
        &self,
        cluster_id: &str,
        command_id: &str,
    ) -> Result<Option<RaftAppliedCommandSummary>, sea_orm::DbErr> {
        raft_applied_command::Entity::find()
            .filter(raft_applied_command::Column::ClusterId.eq(cluster_id.to_owned()))
            .filter(raft_applied_command::Column::CommandId.eq(command_id.to_owned()))
            .one(&self.db)
            .await
            .map(|row| row.map(RaftAppliedCommandSummary::from))
    }

    /// List applied Raft commands for a node.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn list_applied_commands(
        &self,
        node_id: &str,
    ) -> Result<Vec<RaftAppliedCommandSummary>, sea_orm::DbErr> {
        raft_applied_command::Entity::find()
            .filter(raft_applied_command::Column::NodeId.eq(node_id.to_owned()))
            .order_by_asc(raft_applied_command::Column::LogIndex)
            .all(&self.db)
            .await
            .map(|rows| {
                rows.into_iter()
                    .map(RaftAppliedCommandSummary::from)
                    .collect()
            })
    }

    /// Record a Raft membership proposal intent idempotently by `(cluster_id, proposal_id)`.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn record_membership_proposal(
        &self,
        input: RecordRaftMembershipProposal,
    ) -> Result<RaftMembershipProposalSummary, sea_orm::DbErr> {
        if let Some(existing) = raft_membership_proposal::Entity::find()
            .filter(raft_membership_proposal::Column::ClusterId.eq(input.cluster_id.clone()))
            .filter(raft_membership_proposal::Column::ProposalId.eq(input.proposal_id.clone()))
            .one(&self.db)
            .await?
        {
            return Ok(existing.into());
        }

        let now = now_rfc3339();
        raft_membership_proposal::ActiveModel {
            id: Set(new_id("raft_member_prop")),
            cluster_id: Set(input.cluster_id),
            proposal_id: Set(input.proposal_id),
            action: Set(input.action),
            node_id: Set(input.node_id),
            endpoint: Set(input.endpoint),
            status: Set(input.status),
            message: Set(input.message),
            created_by: Set(input.created_by),
            created_at: Set(now.clone()),
            updated_at: Set(now),
        }
        .insert(&self.db)
        .await
        .map(RaftMembershipProposalSummary::from)
    }

    /// Return a membership proposal by cluster/proposal id.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn get_membership_proposal(
        &self,
        cluster_id: &str,
        proposal_id: &str,
    ) -> Result<Option<RaftMembershipProposalSummary>, sea_orm::DbErr> {
        raft_membership_proposal::Entity::find()
            .filter(raft_membership_proposal::Column::ClusterId.eq(cluster_id.to_owned()))
            .filter(raft_membership_proposal::Column::ProposalId.eq(proposal_id.to_owned()))
            .one(&self.db)
            .await
            .map(|row| row.map(RaftMembershipProposalSummary::from))
    }

    /// Update a membership proposal status by cluster/proposal id.
    ///
    /// # Errors
    ///
    /// Returns an error when the underlying operation fails.
    pub async fn update_membership_proposal_status(
        &self,
        cluster_id: &str,
        proposal_id: &str,
        status: &str,
        message: &str,
    ) -> Result<Option<RaftMembershipProposalSummary>, sea_orm::DbErr> {
        let Some(existing) = raft_membership_proposal::Entity::find()
            .filter(raft_membership_proposal::Column::ClusterId.eq(cluster_id.to_owned()))
            .filter(raft_membership_proposal::Column::ProposalId.eq(proposal_id.to_owned()))
            .one(&self.db)
            .await?
        else {
            return Ok(None);
        };
        if existing.status == status && existing.message == message {
            return Ok(Some(existing.into()));
        }

        let now = now_rfc3339();
        let mut active: raft_membership_proposal::ActiveModel = existing.into();
        active.status = Set(status.to_owned());
        active.message = Set(message.to_owned());
        active.updated_at = Set(now);
        active
            .update(&self.db)
            .await
            .map(RaftMembershipProposalSummary::from)
            .map(Some)
    }
}

impl From<raft_metadata::Model> for RaftMetadataSummary {
    fn from(value: raft_metadata::Model) -> Self {
        Self {
            id: value.id,
            cluster_id: value.cluster_id,
            node_id: value.node_id,
            current_term: value.current_term,
            voted_for: value.voted_for,
            commit_index: value.commit_index,
            applied_index: value.applied_index,
            leader_fencing_token: value.leader_fencing_token,
            conf_state: value.conf_state,
            updated_at: value.updated_at,
        }
    }
}

impl From<raft_member::Model> for RaftMemberSummary {
    fn from(value: raft_member::Model) -> Self {
        Self {
            id: value.id,
            node_id: value.node_id,
            endpoint: value.endpoint,
            status: value.status,
            created_at: value.created_at,
            updated_at: value.updated_at,
        }
    }
}

impl From<raft_log_entry::Model> for RaftLogEntrySummary {
    fn from(value: raft_log_entry::Model) -> Self {
        Self {
            id: value.id,
            cluster_id: value.cluster_id,
            node_id: value.node_id,
            log_index: value.log_index,
            term: value.term,
            entry_type: value.entry_type,
            data: value.data,
            context: value.context,
            sync_status: value.sync_status,
            created_at: value.created_at,
            updated_at: value.updated_at,
        }
    }
}

impl From<raft_snapshot::Model> for RaftSnapshotSummary {
    fn from(value: raft_snapshot::Model) -> Self {
        Self {
            id: value.id,
            cluster_id: value.cluster_id,
            node_id: value.node_id,
            snapshot_index: value.snapshot_index,
            term: value.term,
            conf_state: value.conf_state,
            data: value.data,
            created_at: value.created_at,
            updated_at: value.updated_at,
        }
    }
}

impl From<raft_applied_command::Model> for RaftAppliedCommandSummary {
    fn from(value: raft_applied_command::Model) -> Self {
        Self {
            id: value.id,
            cluster_id: value.cluster_id,
            node_id: value.node_id,
            log_index: value.log_index,
            term: value.term,
            command_id: value.command_id,
            command_type: value.command_type,
            payload: value.payload,
            status: value.status,
            message: value.message,
            created_at: value.created_at,
            updated_at: value.updated_at,
        }
    }
}

impl From<raft_membership_proposal::Model> for RaftMembershipProposalSummary {
    fn from(value: raft_membership_proposal::Model) -> Self {
        Self {
            id: value.id,
            cluster_id: value.cluster_id,
            proposal_id: value.proposal_id,
            action: value.action,
            node_id: value.node_id,
            endpoint: value.endpoint,
            status: value.status,
            message: value.message,
            created_by: value.created_by,
            created_at: value.created_at,
            updated_at: value.updated_at,
        }
    }
}
