//! `OpenAPI` document generation.

use utoipa::OpenApi;

use super::{auth, dto, routes};

/// tikee management `OpenAPI` document.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "tikee Management API",
        version = env!("CARGO_PKG_VERSION"),
        description = "HTTP management API for the tikee platform."
    ),
    paths(
        routes::system::system_info,
        routes::metrics::metrics_summary,
        routes::system::cluster_status,
        routes::system::cluster_diagnostics,
        routes::raft::append_entries,
        routes::raft::propose_member_change,
        auth::login,
        auth::me,
        auth::logout,
        routes::users::list_users,
        routes::users::create_user,
        routes::users::update_user,
        routes::users::delete_user,
        routes::scripts::list_scripts,
        routes::scripts::create_script,
        routes::scripts::get_script,
        routes::scripts::update_script,
        routes::scripts::publish_script,
        routes::scripts::rollback_script,
        routes::scripts::delete_script,
        routes::scripts::list_script_versions,
        routes::scripts::diff_script_versions,
        routes::jobs::list_jobs,
        routes::jobs::create_job,
        routes::jobs::trigger_job,
        routes::jobs::list_job_instances,
        routes::jobs::get_job_instance,
        routes::jobs::list_instance_attempts,
        routes::jobs::list_instance_logs,
        routes::audit::list_audit_logs,
        routes::audit::export_audit_logs,
        routes::workers::list_workers,
        routes::workers::dispatch_queue,
        routes::workflows::list_workflows,
        routes::workflows::create_workflow,
        routes::workflows::get_workflow,
        routes::workflows::update_workflow,
        routes::workflows::dry_run_workflow,
        routes::workflows::validate_workflow,
        routes::workflows::run_workflow,
        routes::workflows::get_workflow_instance,
        routes::workflows::advance_workflow_instance,
        routes::workflows::materialize_next_workflow_node,
        routes::workflows::recover_workflow_node,
        routes::workflows::list_workflow_shards,
        routes::workflows::complete_workflow_shard,
    ),
    components(schemas(
        dto::ApiResponse<dto::SystemInfoResponse>,
        dto::ApiResponse<dto::ClusterResponse>,
        dto::ApiResponse<dto::MetricsSummaryResponse>,
        dto::ApiResponse<dto::ClusterDiagnosticsResponse>,
        dto::ApiResponse<dto::RaftMessageResult>,
        dto::ApiResponse<dto::RaftMembershipProposalResponse>,
        dto::ApiResponse<dto::AuthSession>,
        dto::ApiResponse<dto::MeResponse>,
        dto::ApiResponse<dto::AuditLogPage>,
        dto::ApiResponse<dto::EmptyData>,
        dto::ApiResponse<dto::Page>,
        dto::ApiResponse<dto::JobSummary>,
        dto::ApiResponse<dto::JobInstanceSummary>,
        dto::ApiResponse<dto::JobInstancePage>,
        dto::ApiResponse<dto::JobInstanceAttemptPage>,
        dto::ApiResponse<dto::JobInstanceLogPage>,
        dto::ApiResponse<dto::ScriptPage>,
        dto::ApiResponse<tikee_storage::ScriptSummary>,
        dto::ApiResponse<tikee_storage::UserSummary>,
        dto::ApiResponse<Vec<tikee_storage::UserSummary>>,
        dto::ApiResponse<dto::ErrorData>,
        dto::CreateUserRequest,
        dto::UpdateUserRequest,
        dto::CreateScriptRequest,
        dto::UpdateScriptRequest,
        dto::ScriptReleaseRequest,
        tikee_storage::ScriptVersionSummary,
        dto::ScriptDiffResult,
        dto::FieldChange,
        tikee_storage::UserSummary,
        tikee_storage::ScriptSummary,
        dto::ErrorData,
        dto::Page,
        dto::AuditLogQuery,
        dto::SystemInfoResponse,
        dto::ClusterResponse,
        dto::MetricsSummaryResponse,
        dto::MetricsWorkerSummary,
        dto::MetricsInstanceSummary,
        dto::MetricsAlertSummary,
        dto::MetricsGovernanceSummary,
        dto::ClusterDiagnosticsResponse,
        dto::RaftMetadataDiagnostic,
        dto::RaftMemberDiagnostic,
        dto::RaftTransportDiagnostic,
        dto::RaftAppendEntriesRequest,
        dto::RaftWireEntry,
        dto::RaftMessageResult,
        dto::RaftMembershipProposalRequest,
        dto::RaftMembershipProposalResponse,
        tikee_storage::RaftMembershipProposalSummary,
        dto::LoginRequest,
        dto::AuthSession,
        dto::MeResponse,
        dto::EmptyData,
        dto::JobSummary,
        dto::JobInstanceSummary,
        dto::JobInstancePage,
        dto::JobInstanceAttemptSummary,
        dto::JobInstanceAttemptPage,
        dto::JobInstanceLogSummary,
        dto::JobInstanceLogPage,
        dto::ScriptPage,
        dto::CreateJobRequest,
        dto::AuditLogSummary,
        dto::AuditLogPage,
        dto::TriggerJobRequest,
        dto::WorkflowRunRequest,
        dto::WorkflowDryRunResponse,
        dto::WorkerSummary,
        dto::WorkerListResponse,
        tikee_storage::AdvanceWorkflowInput,
        tikee_storage::AdvanceWorkflowResult,
        tikee_storage::MaterializeWorkflowNodeResult,
        tikee_storage::RecoverWorkflowNodeInput,
        tikee_storage::RecoverWorkflowNodeResult,
        tikee_storage::WorkflowSummary,
        tikee_storage::WorkflowDefinition,
        tikee_storage::WorkflowNodeSpec,
        tikee_storage::WorkflowEdgeSpec,
        tikee_storage::WorkflowValidationResult,
        tikee_storage::WorkflowInstanceSummary,
        tikee_storage::WorkflowNodeInstanceSummary,
        tikee_storage::WorkflowShardSummary,
        tikee_storage::CompleteWorkflowShardInput,
        tikee_storage::CompleteWorkflowShardResult,
        tikee_storage::DispatchQueueSummary,
        tikee_storage::QueueOverview,
        crate::http::routes::workflows::CreateWorkflowRequest,
        crate::http::routes::workflows::UpdateWorkflowRequest,
    )),
    tags(
        (name = "system", description = "System and cluster metadata"),
        (name = "raft", description = "Reserved node-to-node Raft transport endpoints"),
        (name = "auth", description = "Development authentication endpoints"),
        (name = "scripts", description = "Script management endpoints"),
        (name = "jobs", description = "Job management endpoints"),
        (name = "audit", description = "Audit log endpoints"),
        (name = "metrics", description = "Operator metrics summary endpoints")
    )
)]
pub struct ApiDoc;
