server:
  port: ${TIKEE_DEMO_SERVER_PORT:18080}

spring:
  application:
    name: tikee-spring-worker-demo
  output:
    ansi:
      enabled: always

tikee:
  worker:
    dry-run: false
    endpoint: http://127.0.0.1:9998
    client-instance-id: spring-demo-worker
    namespace: default
    app: default
    cluster: local
    region: local
    capabilities:
      - java
      - spring-boot
    labels:
      runtime: java
      demo: spring-worker
