// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

type ScriptProcessorBinding struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ScriptId            string                 `protobuf:"bytes,1,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	Version             string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Language            string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Content             []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	VersionId           string                 `protobuf:"bytes,5,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	VersionNumber       uint64                 `protobuf:"varint,6,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	ContentSha256       string                 `protobuf:"bytes,7,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	TimeoutMs           uint64                 `protobuf:"varint,8,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	MaxMemoryBytes      uint64                 `protobuf:"varint,9,opt,name=max_memory_bytes,json=maxMemoryBytes,proto3" json:"max_memory_bytes,omitempty"`
	MaxOutputBytes      uint64                 `protobuf:"varint,10,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	AllowNetwork        bool                   `protobuf:"varint,11,opt,name=allow_network,json=allowNetwork,proto3" json:"allow_network,omitempty"`
	AllowedEnvVars      []string               `protobuf:"bytes,12,rep,name=allowed_env_vars,json=allowedEnvVars,proto3" json:"allowed_env_vars,omitempty"`
	ReadOnlyPaths       []string               `protobuf:"bytes,13,rep,name=read_only_paths,json=readOnlyPaths,proto3" json:"read_only_paths,omitempty"`
	WritablePaths       []string               `protobuf:"bytes,14,rep,name=writable_paths,json=writablePaths,proto3" json:"writable_paths,omitempty"`
	SecretRefs          []string               `protobuf:"bytes,15,rep,name=secret_refs,json=secretRefs,proto3" json:"secret_refs,omitempty"`
	AllowedNetworkHosts []string               `protobuf:"bytes,16,rep,name=allowed_network_hosts,json=allowedNetworkHosts,proto3" json:"allowed_network_hosts,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ScriptProcessorBinding) Reset() {
	*x = ScriptProcessorBinding{}
	mi := &file_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptProcessorBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptProcessorBinding) ProtoMessage() {}

func (x *ScriptProcessorBinding) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptProcessorBinding.ProtoReflect.Descriptor instead.
func (*ScriptProcessorBinding) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{9}
}

func (x *ScriptProcessorBinding) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *ScriptProcessorBinding) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ScriptProcessorBinding) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ScriptProcessorBinding) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ScriptProcessorBinding) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *ScriptProcessorBinding) GetVersionNumber() uint64 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *ScriptProcessorBinding) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

func (x *ScriptProcessorBinding) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ScriptProcessorBinding) GetMaxMemoryBytes() uint64 {
	if x != nil {
		return x.MaxMemoryBytes
	}
	return 0
}

func (x *ScriptProcessorBinding) GetMaxOutputBytes() uint64 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

func (x *ScriptProcessorBinding) GetAllowNetwork() bool {
	if x != nil {
		return x.AllowNetwork
	}
	return false
}

func (x *ScriptProcessorBinding) GetAllowedEnvVars() []string {
	if x != nil {
		return x.AllowedEnvVars
	}
	return nil
}

func (x *ScriptProcessorBinding) GetReadOnlyPaths() []string {
	if x != nil {
		return x.ReadOnlyPaths
	}
	return nil
}

func (x *ScriptProcessorBinding) GetWritablePaths() []string {
	if x != nil {
		return x.WritablePaths
	}
	return nil
}

func (x *ScriptProcessorBinding) GetSecretRefs() []string {
	if x != nil {
		return x.SecretRefs
	}
	return nil
}

func (x *ScriptProcessorBinding) GetAllowedNetworkHosts() []string {
	if x != nil {
		return x.AllowedNetworkHosts
	}
	return nil
}

type WasmProcessorBinding struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScriptId       string                 `protobuf:"bytes,1,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Module         []byte                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	Runtime        string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Entrypoint     string                 `protobuf:"bytes,5,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	TimeoutMs      uint64                 `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	MaxMemoryBytes uint64                 `protobuf:"varint,7,opt,name=max_memory_bytes,json=maxMemoryBytes,proto3" json:"max_memory_bytes,omitempty"`
	Fuel           uint64                 `protobuf:"varint,8,opt,name=fuel,proto3" json:"fuel,omitempty"`
	AllowNetwork   bool                   `protobuf:"varint,9,opt,name=allow_network,json=allowNetwork,proto3" json:"allow_network,omitempty"`
	AllowedEnvVars []string               `protobuf:"bytes,10,rep,name=allowed_env_vars,json=allowedEnvVars,proto3" json:"allowed_env_vars,omitempty"`
	// Immutable script version snapshot identifier when available.
	VersionId string `protobuf:"bytes,11,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	// Monotonic script version snapshot number when available.
	VersionNumber uint64 `protobuf:"varint,12,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	// Lowercase hex SHA-256 digest of module bytes. Workers must verify when present.
	ModuleSha256 string `protobuf:"bytes,13,opt,name=module_sha256,json=moduleSha256,proto3" json:"module_sha256,omitempty"`
	// Reserved signature hook for future PKI-backed module verification.
	ModuleSignature string `protobuf:"bytes,14,opt,name=module_signature,json=moduleSignature,proto3" json:"module_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WasmProcessorBinding) Reset() {
	*x = WasmProcessorBinding{}
	mi := &file_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WasmProcessorBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmProcessorBinding) ProtoMessage() {}

func (x *WasmProcessorBinding) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmProcessorBinding.ProtoReflect.Descriptor instead.
func (*WasmProcessorBinding) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{10}
}

func (x *WasmProcessorBinding) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *WasmProcessorBinding) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WasmProcessorBinding) GetModule() []byte {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *WasmProcessorBinding) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *WasmProcessorBinding) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *WasmProcessorBinding) GetTimeoutMs() uint64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *WasmProcessorBinding) GetMaxMemoryBytes() uint64 {
	if x != nil {
		return x.MaxMemoryBytes
	}
	return 0
}

func (x *WasmProcessorBinding) GetFuel() uint64 {
	if x != nil {
		return x.Fuel
	}
	return 0
}

func (x *WasmProcessorBinding) GetAllowNetwork() bool {
	if x != nil {
		return x.AllowNetwork
	}
	return false
}

func (x *WasmProcessorBinding) GetAllowedEnvVars() []string {
	if x != nil {
		return x.AllowedEnvVars
	}
	return nil
}

func (x *WasmProcessorBinding) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *WasmProcessorBinding) GetVersionNumber() uint64 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *WasmProcessorBinding) GetModuleSha256() string {
	if x != nil {
		return x.ModuleSha256
	}
	return ""
}

func (x *WasmProcessorBinding) GetModuleSignature() string {
	if x != nil {
		return x.ModuleSignature
	}
	return ""
}

type TaskResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerId        string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	InstanceId      string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Success         bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	AssignmentToken string                 `protobuf:"bytes,5,opt,name=assignment_token,json=assignmentToken,proto3" json:"assignment_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{11}
}

func (x *TaskResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskResult) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskResult) GetAssignmentToken() string {
	if x != nil {
		return x.AssignmentToken
	}
	return ""
}

type TaskLog struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerId        string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	InstanceId      string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Level           string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Sequence        int64                  `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	AssignmentToken string                 `protobuf:"bytes,6,opt,name=assignment_token,json=assignmentToken,proto3" json:"assignment_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskLog) Reset() {
	*x = TaskLog{}
	mi := &file_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLog) ProtoMessage() {}

func (x *TaskLog) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLog.ProtoReflect.Descriptor instead.
func (*TaskLog) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{12}
}

func (x *TaskLog) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskLog) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *TaskLog) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *TaskLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskLog) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TaskLog) GetAssignmentToken() string {
	if x != nil {
		return x.AssignmentToken
	}
	return ""
}

type SubscribeTaskLogsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	AfterSequence  int64                  `protobuf:"varint,2,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	ReplayExisting bool                   `protobuf:"varint,3,opt,name=replay_existing,json=replayExisting,proto3" json:"replay_existing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeTaskLogsRequest) Reset() {
	*x = SubscribeTaskLogsRequest{}
	mi := &file_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTaskLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTaskLogsRequest) ProtoMessage() {}

func (x *SubscribeTaskLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTaskLogsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTaskLogsRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeTaskLogsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SubscribeTaskLogsRequest) GetAfterSequence() int64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

func (x *SubscribeTaskLogsRequest) GetReplayExisting() bool {
	if x != nil {
		return x.ReplayExisting
	}
	return false
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\x0ftikee.worker.v1\"\xce\x02\n" +
	"\rWorkerMessage\x12=\n" +
	"\bregister\x18\x01 \x01(\v2\x1f.tikee.worker.v1.RegisterWorkerH\x00R\bregister\x12:\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1a.tikee.worker.v1.HeartbeatH\x00R\theartbeat\x12>\n" +
	"\vtask_result\x18\x03 \x01(\v2\x1b.tikee.worker.v1.TaskResultH\x00R\n" +
	"taskResult\x125\n" +
	"\btask_log\x18\x04 \x01(\v2\x18.tikee.worker.v1.TaskLogH\x00R\ataskLog\x12C\n" +
	"\n" +
	"unregister\x18\x05 \x01(\v2!.tikee.worker.v1.UnregisterWorkerH\x00R\n" +
	"unregisterB\x06\n" +
	"\x04kind\"\xcf\x01\n" +
	"\rServerMessage\x12C\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2!.tikee.worker.v1.WorkerRegisteredH\x00R\n" +
	"registered\x12+\n" +
	"\x04ping\x18\x02 \x01(\v2\x15.tikee.worker.v1.PingH\x00R\x04ping\x12D\n" +
	"\rdispatch_task\x18\x03 \x01(\v2\x1d.tikee.worker.v1.DispatchTaskH\x00R\fdispatchTaskB\x06\n" +
	"\x04kind\"\xc4\x02\n" +
	"\x0eRegisterWorker\x12,\n" +
	"\x12client_instance_id\x18\x01 \x01(\tR\x10clientInstanceId\x12\x10\n" +
	"\x03app\x18\x02 \x01(\tR\x03app\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x18\n" +
	"\acluster\x18\x04 \x01(\tR\acluster\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12C\n" +
	"\x06labels\x18\a \x03(\v2+.tikee.worker.v1.RegisterWorker.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12#\n" +
	"\rfencing_token\x18\x04 \x01(\tR\ffencingToken\"\x99\x01\n" +
	"\x10WorkerRegistered\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12#\n" +
	"\rlease_seconds\x18\x02 \x01(\x04R\fleaseSeconds\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12#\n" +
	"\rfencing_token\x18\x04 \x01(\tR\ffencingToken\"t\n" +
	"\x10UnregisterWorker\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\tR\ffencingToken\"\"\n" +
	"\x04Ping\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"\x86\x02\n" +
	"\fDispatchTask\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12%\n" +
	"\x0eprocessor_name\x18\x04 \x01(\tR\rprocessorName\x12R\n" +
	"\x11processor_binding\x18\x05 \x01(\v2%.tikee.worker.v1.TaskProcessorBindingR\x10processorBinding\x12)\n" +
	"\x10assignment_token\x18\x06 \x01(\tR\x0fassignmentToken\"\x9e\x01\n" +
	"\x14TaskProcessorBinding\x12;\n" +
	"\x04wasm\x18\x01 \x01(\v2%.tikee.worker.v1.WasmProcessorBindingH\x00R\x04wasm\x12A\n" +
	"\x06script\x18\x02 \x01(\v2'.tikee.worker.v1.ScriptProcessorBindingH\x00R\x06scriptB\x06\n" +
	"\x04kind\"\xd8\x04\n" +
	"\x16ScriptProcessorBinding\x12\x1b\n" +
	"\tscript_id\x18\x01 \x01(\tR\bscriptId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"version_id\x18\x05 \x01(\tR\tversionId\x12%\n" +
	"\x0eversion_number\x18\x06 \x01(\x04R\rversionNumber\x12%\n" +
	"\x0econtent_sha256\x18\a \x01(\tR\rcontentSha256\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\b \x01(\x04R\ttimeoutMs\x12(\n" +
	"\x10max_memory_bytes\x18\t \x01(\x04R\x0emaxMemoryBytes\x12(\n" +
	"\x10max_output_bytes\x18\n" +
	" \x01(\x04R\x0emaxOutputBytes\x12#\n" +
	"\rallow_network\x18\v \x01(\bR\fallowNetwork\x12(\n" +
	"\x10allowed_env_vars\x18\f \x03(\tR\x0eallowedEnvVars\x12&\n" +
	"\x0fread_only_paths\x18\r \x03(\tR\rreadOnlyPaths\x12%\n" +
	"\x0ewritable_paths\x18\x0e \x03(\tR\rwritablePaths\x12\x1f\n" +
	"\vsecret_refs\x18\x0f \x03(\tR\n" +
	"secretRefs\x122\n" +
	"\x15allowed_network_hosts\x18\x10 \x03(\tR\x13allowedNetworkHosts\"\xe1\x03\n" +
	"\x14WasmProcessorBinding\x12\x1b\n" +
	"\tscript_id\x18\x01 \x01(\tR\bscriptId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06module\x18\x03 \x01(\fR\x06module\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x05 \x01(\tR\n" +
	"entrypoint\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x04R\ttimeoutMs\x12(\n" +
	"\x10max_memory_bytes\x18\a \x01(\x04R\x0emaxMemoryBytes\x12\x12\n" +
	"\x04fuel\x18\b \x01(\x04R\x04fuel\x12#\n" +
	"\rallow_network\x18\t \x01(\bR\fallowNetwork\x12(\n" +
	"\x10allowed_env_vars\x18\n" +
	" \x03(\tR\x0eallowedEnvVars\x12\x1d\n" +
	"\n" +
	"version_id\x18\v \x01(\tR\tversionId\x12%\n" +
	"\x0eversion_number\x18\f \x01(\x04R\rversionNumber\x12#\n" +
	"\rmodule_sha256\x18\r \x01(\tR\fmoduleSha256\x12)\n" +
	"\x10module_signature\x18\x0e \x01(\tR\x0fmoduleSignature\"\xa9\x01\n" +
	"\n" +
	"TaskResult\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12)\n" +
	"\x10assignment_token\x18\x05 \x01(\tR\x0fassignmentToken\"\xbe\x01\n" +
	"\aTaskLog\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x03R\bsequence\x12)\n" +
	"\x10assignment_token\x18\x06 \x01(\tR\x0fassignmentToken\"\x8b\x01\n" +
	"\x18SubscribeTaskLogsRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12%\n" +
	"\x0eafter_sequence\x18\x02 \x01(\x03R\rafterSequence\x12'\n" +
	"\x0freplay_existing\x18\x03 \x01(\bR\x0ereplayExisting2\xc3\x01\n" +
	"\x13WorkerTunnelService\x12P\n" +
	"\n" +
	"OpenTunnel\x12\x1e.tikee.worker.v1.WorkerMessage\x1a\x1e.tikee.worker.v1.ServerMessage(\x010\x01\x12Z\n" +
	"\x11SubscribeTaskLogs\x12).tikee.worker.v1.SubscribeTaskLogsRequest\x1a\x18.tikee.worker.v1.TaskLog0\x01BBZ@github.com/yhyzgn/tikee/sdks/go/tikee/internal/workerpb;workerpbb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_worker_proto_goTypes = []any{
	(*WorkerMessage)(nil),            // 0: tikee.worker.v1.WorkerMessage
	(*ServerMessage)(nil),            // 1: tikee.worker.v1.ServerMessage
	(*RegisterWorker)(nil),           // 2: tikee.worker.v1.RegisterWorker
	(*Heartbeat)(nil),                // 3: tikee.worker.v1.Heartbeat
	(*WorkerRegistered)(nil),         // 4: tikee.worker.v1.WorkerRegistered
	(*UnregisterWorker)(nil),         // 5: tikee.worker.v1.UnregisterWorker
	(*Ping)(nil),                     // 6: tikee.worker.v1.Ping
	(*DispatchTask)(nil),             // 7: tikee.worker.v1.DispatchTask
	(*TaskProcessorBinding)(nil),     // 8: tikee.worker.v1.TaskProcessorBinding
	(*ScriptProcessorBinding)(nil),   // 9: tikee.worker.v1.ScriptProcessorBinding
	(*WasmProcessorBinding)(nil),     // 10: tikee.worker.v1.WasmProcessorBinding
	(*TaskResult)(nil),               // 11: tikee.worker.v1.TaskResult
	(*TaskLog)(nil),                  // 12: tikee.worker.v1.TaskLog
	(*SubscribeTaskLogsRequest)(nil), // 13: tikee.worker.v1.SubscribeTaskLogsRequest
	nil,                              // 14: tikee.worker.v1.RegisterWorker.LabelsEntry
}
var file_worker_proto_depIdxs = []int32{
	2,  // 0: tikee.worker.v1.WorkerMessage.register:type_name -> tikee.worker.v1.RegisterWorker
	3,  // 1: tikee.worker.v1.WorkerMessage.heartbeat:type_name -> tikee.worker.v1.Heartbeat
	11, // 2: tikee.worker.v1.WorkerMessage.task_result:type_name -> tikee.worker.v1.TaskResult
	12, // 3: tikee.worker.v1.WorkerMessage.task_log:type_name -> tikee.worker.v1.TaskLog
	5,  // 4: tikee.worker.v1.WorkerMessage.unregister:type_name -> tikee.worker.v1.UnregisterWorker
	4,  // 5: tikee.worker.v1.ServerMessage.registered:type_name -> tikee.worker.v1.WorkerRegistered
	6,  // 6: tikee.worker.v1.ServerMessage.ping:type_name -> tikee.worker.v1.Ping
	7,  // 7: tikee.worker.v1.ServerMessage.dispatch_task:type_name -> tikee.worker.v1.DispatchTask
	14, // 8: tikee.worker.v1.RegisterWorker.labels:type_name -> tikee.worker.v1.RegisterWorker.LabelsEntry
	8,  // 9: tikee.worker.v1.DispatchTask.processor_binding:type_name -> tikee.worker.v1.TaskProcessorBinding
	10, // 10: tikee.worker.v1.TaskProcessorBinding.wasm:type_name -> tikee.worker.v1.WasmProcessorBinding
	9,  // 11: tikee.worker.v1.TaskProcessorBinding.script:type_name -> tikee.worker.v1.ScriptProcessorBinding
	0,  // 12: tikee.worker.v1.WorkerTunnelService.OpenTunnel:input_type -> tikee.worker.v1.WorkerMessage
	13, // 13: tikee.worker.v1.WorkerTunnelService.SubscribeTaskLogs:input_type -> tikee.worker.v1.SubscribeTaskLogsRequest
	1,  // 14: tikee.worker.v1.WorkerTunnelService.OpenTunnel:output_type -> tikee.worker.v1.ServerMessage
	12, // 15: tikee.worker.v1.WorkerTunnelService.SubscribeTaskLogs:output_type -> tikee.worker.v1.TaskLog
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	file_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Register)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_TaskResult)(nil),
		(*WorkerMessage_TaskLog)(nil),
		(*WorkerMessage_Unregister)(nil),
	}
	file_worker_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Registered)(nil),
		(*ServerMessage_Ping)(nil),
		(*ServerMessage_DispatchTask)(nil),
	}
	file_worker_proto_msgTypes[8].OneofWrappers = []any{
		(*TaskProcessorBinding_Wasm)(nil),
		(*TaskProcessorBinding_Script)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
