// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: worker.proto

package workerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerTunnelService_OpenTunnel_FullMethodName        = "/tikee.worker.v1.WorkerTunnelService/OpenTunnel"
	WorkerTunnelService_SubscribeTaskLogs_FullMethodName = "/tikee.worker.v1.WorkerTunnelService/SubscribeTaskLogs"
)

// WorkerTunnelServiceClient is the client API for WorkerTunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerTunnelServiceClient interface {
	OpenTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ServerMessage], error)
	SubscribeTaskLogs(ctx context.Context, in *SubscribeTaskLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskLog], error)
}

type workerTunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerTunnelServiceClient(cc grpc.ClientConnInterface) WorkerTunnelServiceClient {
	return &workerTunnelServiceClient{cc}
}

func (c *workerTunnelServiceClient) OpenTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerTunnelService_ServiceDesc.Streams[0], WorkerTunnelService_OpenTunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerTunnelService_OpenTunnelClient = grpc.BidiStreamingClient[WorkerMessage, ServerMessage]

func (c *workerTunnelServiceClient) SubscribeTaskLogs(ctx context.Context, in *SubscribeTaskLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskLog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerTunnelService_ServiceDesc.Streams[1], WorkerTunnelService_SubscribeTaskLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeTaskLogsRequest, TaskLog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerTunnelService_SubscribeTaskLogsClient = grpc.ServerStreamingClient[TaskLog]

// WorkerTunnelServiceServer is the server API for WorkerTunnelService service.
// All implementations must embed UnimplementedWorkerTunnelServiceServer
// for forward compatibility.
type WorkerTunnelServiceServer interface {
	OpenTunnel(grpc.BidiStreamingServer[WorkerMessage, ServerMessage]) error
	SubscribeTaskLogs(*SubscribeTaskLogsRequest, grpc.ServerStreamingServer[TaskLog]) error
	mustEmbedUnimplementedWorkerTunnelServiceServer()
}

// UnimplementedWorkerTunnelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerTunnelServiceServer struct{}

func (UnimplementedWorkerTunnelServiceServer) OpenTunnel(grpc.BidiStreamingServer[WorkerMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method OpenTunnel not implemented")
}
func (UnimplementedWorkerTunnelServiceServer) SubscribeTaskLogs(*SubscribeTaskLogsRequest, grpc.ServerStreamingServer[TaskLog]) error {
	return status.Error(codes.Unimplemented, "method SubscribeTaskLogs not implemented")
}
func (UnimplementedWorkerTunnelServiceServer) mustEmbedUnimplementedWorkerTunnelServiceServer() {}
func (UnimplementedWorkerTunnelServiceServer) testEmbeddedByValue()                             {}

// UnsafeWorkerTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerTunnelServiceServer will
// result in compilation errors.
type UnsafeWorkerTunnelServiceServer interface {
	mustEmbedUnimplementedWorkerTunnelServiceServer()
}

func RegisterWorkerTunnelServiceServer(s grpc.ServiceRegistrar, srv WorkerTunnelServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerTunnelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerTunnelService_ServiceDesc, srv)
}

func _WorkerTunnelService_OpenTunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerTunnelServiceServer).OpenTunnel(&grpc.GenericServerStream[WorkerMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerTunnelService_OpenTunnelServer = grpc.BidiStreamingServer[WorkerMessage, ServerMessage]

func _WorkerTunnelService_SubscribeTaskLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTaskLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerTunnelServiceServer).SubscribeTaskLogs(m, &grpc.GenericServerStream[SubscribeTaskLogsRequest, TaskLog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerTunnelService_SubscribeTaskLogsServer = grpc.ServerStreamingServer[TaskLog]

// WorkerTunnelService_ServiceDesc is the grpc.ServiceDesc for WorkerTunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerTunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tikee.worker.v1.WorkerTunnelService",
	HandlerType: (*WorkerTunnelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenTunnel",
			Handler:       _WorkerTunnelService_OpenTunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeTaskLogs",
			Handler:       _WorkerTunnelService_SubscribeTaskLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "worker.proto",
}
