{{- if .Values.server.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tikeo.name" . }}-server
  namespace: {{ include "tikeo.namespace" . }}
  labels:
    {{- include "tikeo.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  minAvailable: {{ .Values.server.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tikeo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: server
---
{{- end }}
{{- if .Values.web.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tikeo.name" . }}-web
  namespace: {{ include "tikeo.namespace" . }}
  labels:
    {{- include "tikeo.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.web.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tikeo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
{{- end }}
