use sea_orm::{
    ActiveModelTrait, ColumnTrait, DatabaseConnection, EntityTrait, QueryFilter, QueryOrder,
    QuerySelect, Set,
};
use serde::{Deserialize, Serialize};

use crate::entities::{raft_log_entry, raft_member, raft_metadata, raft_snapshot};

use super::util::{new_id, now_rfc3339};

/// Raft metadata upsert input.
#[derive(Debug, Clone)]
pub struct UpsertRaftMetadata {
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable local node id.
    pub node_id: String,
    /// Last known Raft term.
    pub current_term: i64,
    /// Vote target in the current term.
    pub voted_for: Option<String>,
    /// Last committed index.
    pub commit_index: i64,
    /// Last applied index.
    pub applied_index: i64,
    /// Leader fencing token generated by a real consensus runtime, when any.
    pub leader_fencing_token: Option<String>,
}

/// Raft member upsert input.
#[derive(Debug, Clone)]
pub struct UpsertRaftMember {
    /// Stable member node id.
    pub node_id: String,
    /// Peer endpoint reachable through container/K8s networking.
    pub endpoint: String,
    /// Member lifecycle status.
    pub status: String,
}

/// Raft log entry upsert input. Payloads are encoded by the caller.
#[derive(Debug, Clone)]
pub struct UpsertRaftLogEntry {
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable scheduler node id owning this local log.
    pub node_id: String,
    /// Raft log index.
    pub log_index: i64,
    /// Raft term.
    pub term: i64,
    /// raft-rs entry type name.
    pub entry_type: String,
    /// Base64-encoded entry payload bytes.
    pub data: String,
    /// Base64-encoded entry context bytes.
    pub context: Option<String>,
    /// Persistence status used by the future Ready pipeline.
    pub sync_status: String,
}

/// Raft snapshot upsert input. Payloads are encoded by the caller.
#[derive(Debug, Clone)]
pub struct UpsertRaftSnapshot {
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable scheduler node id owning this local snapshot.
    pub node_id: String,
    /// Snapshot index.
    pub snapshot_index: i64,
    /// Snapshot term.
    pub term: i64,
    /// Base64-encoded `ConfState` bytes or JSON marker.
    pub conf_state: Option<String>,
    /// Base64-encoded snapshot data or object-store pointer.
    pub data: Option<String>,
}

/// Stored Raft metadata summary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RaftMetadataSummary {
    /// Metadata row identifier.
    pub id: String,
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable local node id.
    pub node_id: String,
    /// Last known Raft term.
    pub current_term: i64,
    /// Vote target in the current term.
    pub voted_for: Option<String>,
    /// Last committed index.
    pub commit_index: i64,
    /// Last applied index.
    pub applied_index: i64,
    /// Leader fencing token generated by a real consensus runtime, when any.
    pub leader_fencing_token: Option<String>,
    /// Last update timestamp.
    pub updated_at: String,
}

/// Stored Raft member summary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RaftMemberSummary {
    /// Member row identifier.
    pub id: String,
    /// Stable member node id.
    pub node_id: String,
    /// Peer endpoint reachable through container/K8s networking.
    pub endpoint: String,
    /// Member lifecycle status.
    pub status: String,
    /// Creation timestamp.
    pub created_at: String,
    /// Last update timestamp.
    pub updated_at: String,
}

/// Stored Raft log entry summary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RaftLogEntrySummary {
    /// Log row identifier.
    pub id: String,
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable scheduler node id owning this local log.
    pub node_id: String,
    /// Raft log index.
    pub log_index: i64,
    /// Raft term.
    pub term: i64,
    /// raft-rs entry type name.
    pub entry_type: String,
    /// Base64-encoded entry payload bytes.
    pub data: String,
    /// Base64-encoded entry context bytes.
    pub context: Option<String>,
    /// Persistence status used by the future Ready pipeline.
    pub sync_status: String,
    /// Creation timestamp.
    pub created_at: String,
    /// Last update timestamp.
    pub updated_at: String,
}

/// Stored Raft snapshot summary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RaftSnapshotSummary {
    /// Snapshot row identifier.
    pub id: String,
    /// Logical cluster identifier.
    pub cluster_id: String,
    /// Stable scheduler node id owning this local snapshot.
    pub node_id: String,
    /// Snapshot index.
    pub snapshot_index: i64,
    /// Snapshot term.
    pub term: i64,
    /// Base64-encoded `ConfState` bytes or JSON marker.
    pub conf_state: Option<String>,
    /// Base64-encoded snapshot data or object-store pointer.
    pub data: Option<String>,
    /// Creation timestamp.
    pub created_at: String,
    /// Last update timestamp.
    pub updated_at: String,
}

/// Repository for Raft metadata, membership, and future raft-rs durable records.
#[derive(Debug, Clone)]
pub struct RaftRepository {
    db: DatabaseConnection,
}

impl RaftRepository {
    /// Create a repository using the provided database connection.
    #[must_use]
    pub const fn new(db: DatabaseConnection) -> Self {
        Self { db }
    }

    /// Upsert local Raft metadata by `node_id`.
    pub async fn upsert_metadata(
        &self,
        input: UpsertRaftMetadata,
    ) -> Result<RaftMetadataSummary, sea_orm::DbErr> {
        let now = now_rfc3339();
        if let Some(existing) = raft_metadata::Entity::find()
            .filter(raft_metadata::Column::NodeId.eq(input.node_id.clone()))
            .one(&self.db)
            .await?
        {
            let mut active: raft_metadata::ActiveModel = existing.into();
            active.cluster_id = Set(input.cluster_id);
            active.current_term = Set(input.current_term);
            active.voted_for = Set(input.voted_for);
            active.commit_index = Set(input.commit_index);
            active.applied_index = Set(input.applied_index);
            active.leader_fencing_token = Set(input.leader_fencing_token);
            active.updated_at = Set(now);
            return active.update(&self.db).await.map(RaftMetadataSummary::from);
        }

        raft_metadata::ActiveModel {
            id: Set(new_id("raft_meta")),
            cluster_id: Set(input.cluster_id),
            node_id: Set(input.node_id),
            current_term: Set(input.current_term),
            voted_for: Set(input.voted_for),
            commit_index: Set(input.commit_index),
            applied_index: Set(input.applied_index),
            leader_fencing_token: Set(input.leader_fencing_token),
            updated_at: Set(now),
        }
        .insert(&self.db)
        .await
        .map(RaftMetadataSummary::from)
    }

    /// Return local Raft metadata by `node_id`.
    pub async fn get_metadata(
        &self,
        node_id: &str,
    ) -> Result<Option<RaftMetadataSummary>, sea_orm::DbErr> {
        raft_metadata::Entity::find()
            .filter(raft_metadata::Column::NodeId.eq(node_id.to_owned()))
            .one(&self.db)
            .await
            .map(|row| row.map(RaftMetadataSummary::from))
    }

    /// Monotonically update the local applied index for a Raft node.
    ///
    /// Returns the current row when it exists. If the requested index is older than the
    /// stored value, the stored value is preserved.
    pub async fn update_applied_index(
        &self,
        node_id: &str,
        applied_index: i64,
    ) -> Result<Option<RaftMetadataSummary>, sea_orm::DbErr> {
        let Some(existing) = raft_metadata::Entity::find()
            .filter(raft_metadata::Column::NodeId.eq(node_id.to_owned()))
            .one(&self.db)
            .await?
        else {
            return Ok(None);
        };
        if applied_index <= existing.applied_index {
            return Ok(Some(existing.into()));
        }

        let now = now_rfc3339();
        let mut active: raft_metadata::ActiveModel = existing.into();
        active.applied_index = Set(applied_index);
        active.updated_at = Set(now);
        active
            .update(&self.db)
            .await
            .map(RaftMetadataSummary::from)
            .map(Some)
    }

    /// Update only the local leader fencing token for a Raft node.
    pub async fn update_leader_fencing_token(
        &self,
        node_id: &str,
        leader_fencing_token: Option<String>,
    ) -> Result<Option<RaftMetadataSummary>, sea_orm::DbErr> {
        let Some(existing) = raft_metadata::Entity::find()
            .filter(raft_metadata::Column::NodeId.eq(node_id.to_owned()))
            .one(&self.db)
            .await?
        else {
            return Ok(None);
        };
        if existing.leader_fencing_token == leader_fencing_token {
            return Ok(Some(existing.into()));
        }

        let now = now_rfc3339();
        let mut active: raft_metadata::ActiveModel = existing.into();
        active.leader_fencing_token = Set(leader_fencing_token);
        active.updated_at = Set(now);
        active
            .update(&self.db)
            .await
            .map(RaftMetadataSummary::from)
            .map(Some)
    }

    /// Upsert a configured Raft member by `node_id`.
    pub async fn upsert_member(
        &self,
        input: UpsertRaftMember,
    ) -> Result<RaftMemberSummary, sea_orm::DbErr> {
        let now = now_rfc3339();
        if let Some(existing) = raft_member::Entity::find()
            .filter(raft_member::Column::NodeId.eq(input.node_id.clone()))
            .one(&self.db)
            .await?
        {
            let mut active: raft_member::ActiveModel = existing.into();
            active.endpoint = Set(input.endpoint);
            active.status = Set(input.status);
            active.updated_at = Set(now);
            return active.update(&self.db).await.map(RaftMemberSummary::from);
        }

        raft_member::ActiveModel {
            id: Set(new_id("raft_member")),
            node_id: Set(input.node_id),
            endpoint: Set(input.endpoint),
            status: Set(input.status),
            created_at: Set(now.clone()),
            updated_at: Set(now),
        }
        .insert(&self.db)
        .await
        .map(RaftMemberSummary::from)
    }

    /// List all configured Raft members.
    pub async fn list_members(&self) -> Result<Vec<RaftMemberSummary>, sea_orm::DbErr> {
        raft_member::Entity::find()
            .all(&self.db)
            .await
            .map(|rows| rows.into_iter().map(RaftMemberSummary::from).collect())
    }

    /// Upsert a local raft-rs log entry by `(node_id, log_index)`.
    pub async fn upsert_log_entry(
        &self,
        input: UpsertRaftLogEntry,
    ) -> Result<RaftLogEntrySummary, sea_orm::DbErr> {
        let now = now_rfc3339();
        if let Some(existing) = raft_log_entry::Entity::find()
            .filter(raft_log_entry::Column::NodeId.eq(input.node_id.clone()))
            .filter(raft_log_entry::Column::LogIndex.eq(input.log_index))
            .one(&self.db)
            .await?
        {
            let mut active: raft_log_entry::ActiveModel = existing.into();
            active.cluster_id = Set(input.cluster_id);
            active.term = Set(input.term);
            active.entry_type = Set(input.entry_type);
            active.data = Set(input.data);
            active.context = Set(input.context);
            active.sync_status = Set(input.sync_status);
            active.updated_at = Set(now);
            return active.update(&self.db).await.map(RaftLogEntrySummary::from);
        }

        raft_log_entry::ActiveModel {
            id: Set(new_id("raft_log")),
            cluster_id: Set(input.cluster_id),
            node_id: Set(input.node_id),
            log_index: Set(input.log_index),
            term: Set(input.term),
            entry_type: Set(input.entry_type),
            data: Set(input.data),
            context: Set(input.context),
            sync_status: Set(input.sync_status),
            created_at: Set(now.clone()),
            updated_at: Set(now),
        }
        .insert(&self.db)
        .await
        .map(RaftLogEntrySummary::from)
    }

    /// List local raft-rs log entries from `from_index` inclusive.
    pub async fn list_log_entries(
        &self,
        node_id: &str,
        from_index: i64,
        limit: u64,
    ) -> Result<Vec<RaftLogEntrySummary>, sea_orm::DbErr> {
        raft_log_entry::Entity::find()
            .filter(raft_log_entry::Column::NodeId.eq(node_id.to_owned()))
            .filter(raft_log_entry::Column::LogIndex.gte(from_index))
            .order_by_asc(raft_log_entry::Column::LogIndex)
            .limit(limit)
            .all(&self.db)
            .await
            .map(|rows| rows.into_iter().map(RaftLogEntrySummary::from).collect())
    }

    /// Upsert a local raft-rs snapshot by `(node_id, snapshot_index)`.
    pub async fn upsert_snapshot(
        &self,
        input: UpsertRaftSnapshot,
    ) -> Result<RaftSnapshotSummary, sea_orm::DbErr> {
        let now = now_rfc3339();
        if let Some(existing) = raft_snapshot::Entity::find()
            .filter(raft_snapshot::Column::NodeId.eq(input.node_id.clone()))
            .filter(raft_snapshot::Column::SnapshotIndex.eq(input.snapshot_index))
            .one(&self.db)
            .await?
        {
            let mut active: raft_snapshot::ActiveModel = existing.into();
            active.cluster_id = Set(input.cluster_id);
            active.term = Set(input.term);
            active.conf_state = Set(input.conf_state);
            active.data = Set(input.data);
            active.updated_at = Set(now);
            return active.update(&self.db).await.map(RaftSnapshotSummary::from);
        }

        raft_snapshot::ActiveModel {
            id: Set(new_id("raft_snapshot")),
            cluster_id: Set(input.cluster_id),
            node_id: Set(input.node_id),
            snapshot_index: Set(input.snapshot_index),
            term: Set(input.term),
            conf_state: Set(input.conf_state),
            data: Set(input.data),
            created_at: Set(now.clone()),
            updated_at: Set(now),
        }
        .insert(&self.db)
        .await
        .map(RaftSnapshotSummary::from)
    }
}

impl From<raft_metadata::Model> for RaftMetadataSummary {
    fn from(value: raft_metadata::Model) -> Self {
        Self {
            id: value.id,
            cluster_id: value.cluster_id,
            node_id: value.node_id,
            current_term: value.current_term,
            voted_for: value.voted_for,
            commit_index: value.commit_index,
            applied_index: value.applied_index,
            leader_fencing_token: value.leader_fencing_token,
            updated_at: value.updated_at,
        }
    }
}

impl From<raft_member::Model> for RaftMemberSummary {
    fn from(value: raft_member::Model) -> Self {
        Self {
            id: value.id,
            node_id: value.node_id,
            endpoint: value.endpoint,
            status: value.status,
            created_at: value.created_at,
            updated_at: value.updated_at,
        }
    }
}

impl From<raft_log_entry::Model> for RaftLogEntrySummary {
    fn from(value: raft_log_entry::Model) -> Self {
        Self {
            id: value.id,
            cluster_id: value.cluster_id,
            node_id: value.node_id,
            log_index: value.log_index,
            term: value.term,
            entry_type: value.entry_type,
            data: value.data,
            context: value.context,
            sync_status: value.sync_status,
            created_at: value.created_at,
            updated_at: value.updated_at,
        }
    }
}

impl From<raft_snapshot::Model> for RaftSnapshotSummary {
    fn from(value: raft_snapshot::Model) -> Self {
        Self {
            id: value.id,
            cluster_id: value.cluster_id,
            node_id: value.node_id,
            snapshot_index: value.snapshot_index,
            term: value.term,
            conf_state: value.conf_state,
            data: value.data,
            created_at: value.created_at,
            updated_at: value.updated_at,
        }
    }
}
