#!/usr/bin/env python3
"""Generate a human-readable Kind Raft HA validation report from evidence files."""

from __future__ import annotations

import csv
import datetime as dt
import json
import math
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


def read_json(path: Path, default: Any = None) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError):
        return default


def read_text(path: Path, default: str = "") -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except FileNotFoundError:
        return default


def load_cases(report_dir: Path) -> list[dict[str, Any]]:
    candidates = sorted(report_dir.glob("*-cases.jsonl"))
    if not candidates:
        return []
    cases: list[dict[str, Any]] = []
    for line in candidates[-1].read_text(encoding="utf-8").splitlines():
        if line.strip():
            try:
                cases.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return cases


def status_of(cases: list[dict[str, Any]], case_id: str) -> str:
    for case in reversed(cases):
        if case.get("id") == case_id:
            return "✅" if case.get("status") == "passed" else "❌"
    return "⬜"


def case_message(cases: list[dict[str, Any]], case_id: str) -> str:
    for case in reversed(cases):
        if case.get("id") == case_id:
            return str(case.get("message") or "")
    return "未记录"


def latest_json(report_dir: Path, pattern: str) -> dict[str, Any]:
    files = sorted(report_dir.glob(pattern))
    return read_json(files[-1], {}) if files else {}


def status_counts_from_db(db: dict[str, Any], key: str) -> dict[str, int]:
    counts: Counter[str] = Counter()
    for row in db.get(key) or []:
        counts[str(row.get("status") or "unknown")] += 1
    return dict(sorted(counts.items()))


def count_unique(values: list[Any]) -> int:
    return len({value for value in values if value not in (None, "")})


def clamp_score(value: float) -> int:
    if math.isnan(value) or math.isinf(value):
        return 0
    return max(0, min(100, round(value)))


def svg_bar_chart(title: str, counts: dict[str, int], out: Path) -> None:
    width = 860
    bar_h = 30
    gap = 12
    margin_l = 230
    margin_r = 40
    margin_t = 68
    height = margin_t + max(1, len(counts)) * (bar_h + gap) + 40
    max_v = max(counts.values(), default=1)
    chart_w = width - margin_l - margin_r
    rows = []
    for idx, (label, value) in enumerate(counts.items() or {"no-data": 0}.items()):
        y = margin_t + idx * (bar_h + gap)
        bar_w = 0 if max_v == 0 else int(chart_w * value / max_v)
        safe_label = (
            str(label).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        )
        rows.append(
            f'<text x="20" y="{y + 21}" font-size="13" fill="#253042">{safe_label}</text>'
            f'<rect x="{margin_l}" y="{y}" width="{bar_w}" height="{bar_h}" rx="8" fill="#2f6fed" />'
            f'<text x="{margin_l + bar_w + 10}" y="{y + 21}" font-size="13" fill="#253042">{value}</text>'
        )
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
  <rect width="100%" height="100%" rx="18" fill="#f8fafc" />
  <text x="20" y="34" font-size="22" font-weight="700" fill="#0f172a">{title}</text>
  <text x="20" y="54" font-size="12" fill="#64748b">Generated by scripts/generate-kind-ha-report.py</text>
  {''.join(rows)}
</svg>
'''
    out.write_text(svg, encoding="utf-8")


def svg_score_chart(scores: dict[str, int], out: Path) -> None:
    width = 900
    height = 360
    rows = []
    for idx, (label, value) in enumerate(scores.items()):
        y = 60 + idx * 48
        color = "#16a34a" if value >= 90 else "#f59e0b" if value >= 70 else "#dc2626"
        rows.append(
            f'<text x="30" y="{y + 22}" font-size="14" fill="#111827">{label}</text>'
            f'<rect x="260" y="{y}" width="560" height="26" rx="13" fill="#e5e7eb" />'
            f'<rect x="260" y="{y}" width="{int(560 * value / 100)}" height="26" rx="13" fill="{color}" />'
            f'<text x="835" y="{y + 20}" font-size="14" font-weight="700" fill="#111827">{value}</text>'
        )
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">
  <rect width="100%" height="100%" rx="18" fill="#fff7ed" />
  <text x="30" y="34" font-size="22" font-weight="700" fill="#111827">HA Validation Indices</text>
  {''.join(rows)}
</svg>
'''
    out.write_text(svg, encoding="utf-8")


def rel(report_dir: Path, path: str | Path) -> str:
    p = Path(path)
    if not p.is_absolute():
        p = report_dir / p
    try:
        return p.relative_to(report_dir).as_posix()
    except ValueError:
        return p.as_posix()


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: generate-kind-ha-report.py <report-dir>", file=sys.stderr)
        return 2
    report_dir = Path(sys.argv[1]).resolve()
    report_dir.mkdir(parents=True, exist_ok=True)

    cases = load_cases(report_dir)
    run_summaries = sorted(report_dir.glob("kind-raft-ha-e2e-*-summary.json"))
    summary = read_json(run_summaries[-1], {}) if run_summaries else latest_json(report_dir, "summary.stdout.json")
    smoke_reports = sorted(
        path for path in report_dir.glob("kind-raft-ha-e2e-*.json")
        if not path.name.endswith("-summary.json")
    )
    smoke = read_json(smoke_reports[-1], {}) if smoke_reports else {}
    placement_initial = read_json(report_dir / "server-pod-placement-initial-summary.json", {})
    placement_after_gateway = read_json(report_dir / "server-pod-placement-after-gateway-poweroff-summary.json", {})
    service_initial = read_json(report_dir / "service-probe-initial-summary.json", {})
    service_after = read_json(report_dir / "service-probe-after-failover-summary.json", {})
    gateway = read_json(report_dir / "gateway-reroute-summary.json", {})
    db_before = read_json(report_dir / "db-evidence-before-failover.json", {})
    db_after = read_json(report_dir / "db-evidence-after-failover.json", {})
    db_gateway = read_json(report_dir / "db-evidence-after-gateway-reroute.json", {})
    failover_text = read_text(report_dir / "failover-summary.txt")

    passed_cases = sum(1 for c in cases if c.get("status") == "passed")
    failed_cases = sum(1 for c in cases if c.get("status") not in ("passed", None))

    replicas = int(summary.get("serverReplicas") or placement_initial.get("serverReplicas") or 0)
    unique_initial = int(placement_initial.get("uniqueNodes") or 0)
    unique_after_gateway = int(placement_after_gateway.get("uniqueNodes") or 0)
    spread_ok = bool(placement_initial.get("antiAffinitySatisfied")) and bool(
        placement_after_gateway.get("antiAffinitySatisfied", placement_initial.get("antiAffinitySatisfied"))
    )

    lb_counts: Counter[str] = Counter()
    for source in (service_initial.get("countsByNode") or {}, service_after.get("countsByNode") or {}):
        lb_counts.update({str(k): int(v) for k, v in source.items()})
    lb_requests = int(service_initial.get("requests") or 0) + int(service_after.get("requests") or 0)
    lb_unique = count_unique(list(lb_counts.keys()))
    lb_coverage = (lb_unique / replicas) if replicas else 0
    lb_skew = max(
        float(service_initial.get("maxAbsoluteSkew") or 0),
        float(service_after.get("maxAbsoluteSkew") or 0),
    )

    ownership_before = db_before.get("clusterShardOwnership") or []
    ownership_after = db_after.get("clusterShardOwnership") or []
    owner_epochs_before = [row.get("epoch") for row in ownership_before]
    owner_epochs_after = [row.get("epoch") for row in ownership_after]
    max_epoch_before = max([int(e) for e in owner_epochs_before if e is not None] or [0])
    max_epoch_after = max([int(e) for e in owner_epochs_after if e is not None] or [0])
    owners_before = count_unique([row.get("ownerNodeId") for row in ownership_before])
    owners_after = count_unique([row.get("ownerNodeId") for row in ownership_after])
    fencing_rows_after = sum(1 for row in ownership_after if row.get("hasFencingToken"))

    outbox_status_before = status_counts_from_db(db_before, "workerDispatchOutbox")
    outbox_status_after = status_counts_from_db(db_after, "workerDispatchOutbox")
    outbox_status_gateway = status_counts_from_db(db_gateway, "workerDispatchOutbox")

    leader_before = summary.get("leaderBefore") or re.search(r"leaderBefore=(\S+)", failover_text or "")
    if hasattr(leader_before, "group"):
        leader_before = leader_before.group(1)
    leader_after = summary.get("leaderAfter") or re.search(r"leaderAfter=(\S+)", failover_text or "")
    if hasattr(leader_after, "group"):
        leader_after = leader_after.group(1)

    anti_affinity_index = clamp_score(100 * min(unique_initial, unique_after_gateway or unique_initial) / replicas) if replicas else 0
    lb_index = clamp_score(100 * min(1.0, lb_coverage) - min(25, lb_skew))
    epoch_index = clamp_score(
        45 * bool(status_of(cases, "fault-drill") == "✅")
        + 25 * bool(max_epoch_after >= max_epoch_before)
        + 20 * bool(fencing_rows_after > 0)
        + 10 * bool(leader_after)
    )
    outbox_index = clamp_score(
        50 * bool(gateway.get("rerouteObserved"))
        + 20 * bool(gateway.get("oldGateway") and gateway.get("newGateway") and gateway.get("oldGateway") != gateway.get("newGateway"))
        + 20 * bool(status_of(cases, "gateway-reroute-dispatch") == "✅")
        + 10 * bool((gateway.get("newGatewayRowsAfter") or 0) > 0)
    )
    evidence_expected = [
        "kind-config.yaml",
        "server-pod-placement-initial-summary.json",
        "service-probe-initial-summary.json",
        "service-probe-after-failover-summary.json",
        "gateway-reroute-summary.json",
        "db-evidence-before-failover.json",
        "db-evidence-after-failover.json",
        "fault-drill.log",
        "summary.stdout.json",
    ]
    evidence_index = clamp_score(100 * sum((report_dir / p).exists() for p in evidence_expected) / len(evidence_expected))
    ha_confidence = clamp_score(
        anti_affinity_index * 0.20
        + lb_index * 0.15
        + epoch_index * 0.25
        + outbox_index * 0.25
        + evidence_index * 0.15
        - failed_cases * 8
    )

    scores = {
        "HA confidence": ha_confidence,
        "Anti-affinity placement": anti_affinity_index,
        "Epoch fencing": epoch_index,
        "Outbox reroute": outbox_index,
        "Service LB distribution": lb_index,
        "Evidence completeness": evidence_index,
    }

    svg_bar_chart("ClusterIP Service probe counts", dict(sorted(lb_counts.items())), report_dir / "chart-service-lb.svg")
    svg_bar_chart("Outbox status after chaos", outbox_status_gateway or outbox_status_after, report_dir / "chart-outbox-status.svg")
    owner_counts = Counter(str(row.get("ownerNodeId") or "unknown") for row in ownership_after)
    svg_bar_chart("Shard ownership after failover", dict(sorted(owner_counts.items())), report_dir / "chart-shard-ownership.svg")
    svg_score_chart(scores, report_dir / "chart-ha-indices.svg")

    metrics_rows = [
        ("server_replicas", replicas),
        ("kind_worker_nodes", summary.get("kindWorkerNodes") or 0),
        ("initial_unique_server_nodes", unique_initial),
        ("after_gateway_unique_server_nodes", unique_after_gateway),
        ("service_probe_requests", lb_requests),
        ("service_probe_unique_nodes", lb_unique),
        ("service_probe_coverage_ratio", round(lb_coverage, 4)),
        ("service_probe_max_abs_skew", round(lb_skew, 4)),
        ("ownership_rows_before", len(ownership_before)),
        ("ownership_rows_after", len(ownership_after)),
        ("ownership_unique_owners_before", owners_before),
        ("ownership_unique_owners_after", owners_after),
        ("ownership_max_epoch_before", max_epoch_before),
        ("ownership_max_epoch_after", max_epoch_after),
        ("outbox_rows_after_gateway", len(db_gateway.get("workerDispatchOutbox") or [])),
        ("gateway_reroute_observed", int(bool(gateway.get("rerouteObserved")))),
        ("passed_cases", passed_cases),
        ("failed_cases", failed_cases),
        *[(f"index_{k.lower().replace(' ', '_').replace('-', '_')}", v) for k, v in scores.items()],
    ]
    with (report_dir / "kind-ha-metrics.csv").open("w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["metric", "value"])
        writer.writerows(metrics_rows)

    checklist = [
        ("T00", "Preflight/tool install", "kind-cluster-ready", "Kind cluster reachable; local tools resolved/installed"),
        ("T01", "Multi-node Kind topology", "kind-cluster-ready", f"worker nodes={summary.get('kindWorkerNodes')}; server replicas={replicas}"),
        ("T02", "Pod anti-affinity/topology spread", "pod-anti-affinity-initial", f"initial unique nodes={unique_initial}; after gateway unique nodes={unique_after_gateway}"),
        ("T03", "Raft bootstrap/rollout gate", "rollout-before-failover", f"owners before={owners_before}; fencing rows after={fencing_rows_after}"),
        ("T04", "API pod != Worker gateway pod", "pod-selection", f"apiPod={summary.get('apiPod')}; gateway={summary.get('workerGatewayPod') or summary.get('workerGatewayPodBeforePoweroff')}"),
        ("T05", "Pre-failover dispatch", "pre-failover-dispatch", "demo.echo completed before failover"),
        ("T06", "Old Owner Full GC/zombie recovery approximation", "fault-drill", f"leaderBefore={leader_before}; leaderAfter={leader_after}; epoch {max_epoch_before}->{max_epoch_after}"),
        ("C01", "Chaos: old owner zombie simulation", "fault-drill", "leader pod delete plus rollout gate validates recovery path"),
        ("T07", "Web/API Service LB rotation", "incluster-service-probe-after-failover", f"requests={lb_requests}; unique nodes={lb_unique}; skew={lb_skew:.2f}"),
        ("T08", "Gateway disconnect + Worker reconnect reroute", "gateway-poweroff-reroute", f"old={gateway.get('oldGateway')}; new={gateway.get('newGateway')}; reroute={gateway.get('rerouteObserved')}"),
        ("C02", "Chaos: force-kill gateway node", "gateway-poweroff-reroute", "kubectl force delete approximates sudden gateway poweroff"),
        ("T09", "Post-chaos dispatch", "post-failover-dispatch", "demo.echo completed after leader and gateway chaos"),
        ("T10", "Evidence/report bundle", "kind-final-report", "Markdown/JSON/CSV/SVG generated"),
    ]

    # Self-record the final report case if not present in the smoke case list yet.
    if not any(c.get("id") == "kind-final-report" for c in cases):
        cases.append(
            {
                "id": "kind-final-report",
                "status": "passed",
                "evidence": "kind-ha-validation-report.md kind-ha-validation-summary.json kind-ha-metrics.csv chart-ha-indices.svg",
                "message": "generated final Kind HA validation evidence bundle",
                "recorded_at": dt.datetime.now(dt.UTC).isoformat(),
            }
        )

    report_md = report_dir / "kind-ha-validation-report.md"
    generated_at = dt.datetime.now(dt.UTC).isoformat()
    verdict = "通过" if failed_cases == 0 and ha_confidence >= 80 else "需复核"
    lines = [
        "# Tikeo Kind Raft FSOD HA Validation Report",
        "",
        f"- Generated at: `{generated_at}`",
        f"- Evidence directory: `{report_dir}`",
        f"- Verdict: **{verdict}**",
        f"- HA confidence index: **{ha_confidence}/100**",
        "",
        "## 1. Test narrative",
        "",
        "本次验证在单机上创建多节点 Kind 集群，通过 required Pod Anti-Affinity 和 topology spread 将 4 个 Tikeo Server Pod 分散到 4 个不同 Kind worker node，以尽量逼近生产 Kubernetes 的故障域调度语义。测试覆盖 Raft owner failover、旧 owner/僵死恢复的 Epoch Fencing、API Service 负载均衡轮询、Worker Gateway 强杀后的 Worker 重连以及 durable Outbox reroute。",
        "",
        "Kind 无法完全等价于云厂商多可用区、云 LB、真实 WAF/Ingress 或远端持久盘故障，但它可以真实运行 Kubernetes 调度器、Service、Pod 生命周期、强制删除、StatefulSet 重建、PDB 等对象语义；因此该报告定位为个人开发者本地近生产 HA 验收，而非最终云环境验收。",
        "",
        "## 2. Environment",
        "",
        f"- Kind cluster: `{summary.get('kindCluster')}`",
        f"- Kind node image: `{summary.get('kindNodeImage')}`",
        f"- Namespace: `{summary.get('namespace')}`",
        f"- Kind worker nodes: `{summary.get('kindWorkerNodes')}`",
        f"- Server replicas: `{replicas}`",
        f"- API pod: `{summary.get('apiPod')}`",
        f"- Worker gateway before poweroff: `{summary.get('workerGatewayPodBeforePoweroff')}`",
        f"- Worker gateway after poweroff: `{summary.get('workerGatewayPodAfterPoweroff') or summary.get('workerGatewayPod')}`",
        "",
        "## 3. Checklist results",
        "",
        "| Status | ID | Item | Actual output | Evidence |",
        "| --- | --- | --- | --- | --- |",
    ]
    for test_id, item, case_id, actual in checklist:
        st = status_of(cases, case_id)
        msg = case_message(cases, case_id)
        lines.append(f"| {st} | {test_id} | {item} | {actual}; {msg} | `{case_id}` |")
    lines += [
        "",
        "## 4. Numeric metrics",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
    ]
    for key, value in metrics_rows:
        lines.append(f"| `{key}` | `{value}` |")
    lines += [
        "",
        "## 5. Indices",
        "",
        "| Index | Score | Meaning |",
        "| --- | ---: | --- |",
        f"| HA confidence | {ha_confidence} | 综合 Anti-Affinity、Epoch Fencing、Outbox Reroute、Service LB、证据完整性 |",
        f"| Anti-affinity placement | {anti_affinity_index} | Server Pod 是否分散到独立 Kind worker node |",
        f"| Epoch fencing | {epoch_index} | 旧 owner 失效/恢复后 stale token 是否被拒绝，且新 owner 可继续调度 |",
        f"| Outbox reroute | {outbox_index} | Gateway 强杀后 durable Outbox 是否移动到 Worker 新会话 |",
        f"| Service LB distribution | {lb_index} | ClusterIP API 请求是否覆盖多个 Server Pod 且偏斜可接受 |",
        f"| Evidence completeness | {evidence_index} | 关键原始证据文件是否齐全 |",
        "",
        "![HA indices](chart-ha-indices.svg)",
        "",
        "## 6. Charts",
        "",
        "![Service load balancing](chart-service-lb.svg)",
        "",
        "![Outbox status](chart-outbox-status.svg)",
        "",
        "![Shard ownership](chart-shard-ownership.svg)",
        "",
        "## 7. Key evidence files",
        "",
    ]
    for path in evidence_expected + [
        "gateway-reroute-summary.json",
        "kind-ha-metrics.csv",
        "chart-service-lb.svg",
        "chart-outbox-status.svg",
        "chart-shard-ownership.svg",
        "chart-ha-indices.svg",
    ]:
        exists = "✅" if (report_dir / path).exists() else "❌"
        lines.append(f"- {exists} `{path}`")
    lines += [
        "",
        "## 8. Raw summaries",
        "",
        "### Pod placement",
        "",
        "```json",
        json.dumps({"initial": placement_initial, "afterGatewayPoweroff": placement_after_gateway}, ensure_ascii=False, indent=2),
        "```",
        "",
        "### Service probe",
        "",
        "```json",
        json.dumps({"initial": service_initial, "afterFailover": service_after}, ensure_ascii=False, indent=2),
        "```",
        "",
        "### Gateway reroute",
        "",
        "```json",
        json.dumps(gateway, ensure_ascii=False, indent=2),
        "```",
        "",
        "### Outbox statuses",
        "",
        "```json",
        json.dumps({"beforeFailover": outbox_status_before, "afterGatewayReroute": outbox_status_gateway, "afterFailover": outbox_status_after}, ensure_ascii=False, indent=2),
        "```",
        "",
        "## 9. Limitations",
        "",
        "- Kind 的多节点运行在同一台物理机上，不能证明跨机器、跨机架、跨 AZ 网络和磁盘故障模型。",
        "- `kubectl delete pod --force --grace-period=0` 能逼近进程/节点突然消失，但不是云主机真实断电的完整等价物。",
        "- 本报告验证 Kubernetes 对象语义、调度分散、Raft failover、Outbox 状态机和 Worker reconnect；真实云环境仍需补充云 LB/Ingress/WAF、存储 HA、网络抖动和资源压力测试。",
        "",
    ]
    report_md.write_text("\n".join(lines), encoding="utf-8")

    machine_summary = {
        "generatedAt": generated_at,
        "report": str(report_md),
        "verdict": verdict,
        "scores": scores,
        "metrics": dict(metrics_rows),
        "cases": cases,
        "evidenceDirectory": str(report_dir),
    }
    (report_dir / "kind-ha-validation-summary.json").write_text(
        json.dumps(machine_summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(machine_summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
